In [1]:
import duckdb
import pandas as pd
import os

In [3]:
import os

def save_sql_to_file(sql_string: str, script_name: str):
    """
    Creates a storage folder (if it doesn't exist) and writes the given SQL string
    to a .sql file within that folder. If a file with the same base name exists,
    it prepends an increasing number (1, 2, 3, ...) to the filename.

    Args:
        sql_string: The SQL query string to be saved.
        script_name: The base name of the script (used for the filename).
    """
    return None # temp disable
    folder_name = "C:\\lopu-kg-test\\project\\src\\main\\sql_for_pipelines"

    # Create the storage folder if it doesn't exist
    if not os.path.exists(folder_name):
        try:
            os.makedirs(folder_name)
            print(f"Folder '{folder_name}' created successfully.")
        except OSError as e:
            print(f"Error creating folder '{folder_name}': {e}")
            return

    base_filename = f"{script_name}.sql"
    counter = 1
    file_path = os.path.join(folder_name, f"{counter}_{base_filename}")

    while os.path.exists(file_path):
        counter += 1
        file_path = os.path.join(folder_name, f"{counter}_{base_filename}")

    # Write the SQL string to the file
    try:
        with open(file_path, "w") as f:
            f.write(sql_string)
        print(f"SQL query successfully written to '{file_path}'.")
    except IOError as e:
        print(f"Error writing to file '{file_path}': {e}")

In [1]:
import duckdb

def get_duckdb_query_stats(conn: duckdb.DuckDBPyConnection, query: str) -> dict:
    """Executes a DuckDB query and returns its statistics."""
    try:
        conn.execute(query)
        #Get the latest query execution info.
        result = conn.execute("SELECT rows, execution_time FROM duckdb_queries ORDER BY finished DESC LIMIT 1").fetchone()
        if result:
            rows, execution_time = result
            return {"rows": rows, "execution_time": execution_time}
        else:
            return {"error": "Could not retrieve query statistics."}

    except duckdb.Error as e:
        return {"error": str(e)}

def get_duckdb_copy_stats(conn: duckdb.DuckDBPyConnection, copy_command: str) -> dict:
    """Executes a DuckDB COPY command and returns its statistics."""
    try:
        conn.execute(copy_command)
        #Get the latest copy command execution info.
        result = conn.execute("SELECT rows, bytes_written, execution_time FROM duckdb_queries ORDER BY finished DESC LIMIT 1").fetchone()
        if result:
            rows, bytes_written, execution_time = result
            return {"rows": rows, "bytes_written": bytes_written, "execution_time": execution_time}
        else:
            return {"error": "Could not retrieve copy statistics."}

    except duckdb.Error as e:
        return {"error": str(e)}

In [3]:
import xml.etree.ElementTree as ET
import pandas as pd
import os

def xml_to_dataframe(xml_file_path):
    """
    Parses an XML file and converts it into a pandas DataFrame.

    Args:
        xml_file_path (str): The path to the XML file.

    Returns:
        pandas.DataFrame: The DataFrame containing the XML data, or None if an error occurs.
    """
    try:
        tree = ET.parse(xml_file_path)
        root = tree.getroot()

        data = []
        for action in root:
            action_data = {}
            # Extract Action attributes
            for key, value in action.attrib.items():
                action_data["Action." + key.split("}")[-1]] = value

            for element in action:
                for key, column0 in element.attrib.items():
                    action_data["Customer." + key.split("}")[-1]] = column0 # value, oli siin enne 04.04 muudatus
                if len(element) == 0:  # Simple element
                    action_data[element.tag.split("}")[-1]] = element.text
                else:  # Nested element
                    for sub_element in element:
                        for key, value in sub_element.attrib.items():
                            action_data["Account." + key.split("}")[-1]] = value
                        if len(sub_element) == 0:
                            action_data[element.tag.split("}")[-1] + "." + sub_element.tag.split("}")[-1]] = sub_element.text
                        else:
                            for sub_sub_element in sub_element:
                                if len(sub_sub_element) == 0:
                                    action_data[element.tag.split("}")[-1] + "." + sub_element.tag.split("}")[-1] + "." + sub_sub_element.tag.split("}")[-1]] = sub_sub_element.text
                                else:
                                    for sub_sub_sub_element in sub_sub_element:
                                        action_data[element.tag.split("}")[-1] + "." + sub_element.tag.split("}")[-1] + "." + sub_sub_element.tag.split("}")[-1] + "." + sub_sub_sub_element.tag.split("}")[-1]] = sub_sub_sub_element.text
            data.append(action_data)

        df = pd.DataFrame(data)
        return df

    except Exception as e:
        print(f"Error processing XML file: {e}")
        return None

path_to_xml = "C:\lopu-kg-test\project\src\data\Batch1\CustomerMgmt.xml"

xml_dataframe = xml_to_dataframe(path_to_xml)

In [4]:
def rename_columns(df):
    """
    Renames DataFrame columns by extracting the last part after '.', 
    and appends a counter if duplicates are found.

    Args:
        df (pd.DataFrame): The DataFrame to rename columns.

    Returns:
        pd.DataFrame: The DataFrame with renamed columns.
    """
    new_columns = []
    seen_columns = {}  # Track seen column names and their counts

    for col in df.columns:
        parts = col.split('.')
        new_col = parts[-1]  # Extract the last part

        if new_col in seen_columns:
            seen_columns[new_col] += 1
            new_col = f"{new_col}_{seen_columns[new_col]}"  # Append a counter
        else:
            seen_columns[new_col] = 0

        new_columns.append(new_col)

    df.columns = new_columns
    return df


xml_dataframe = rename_columns(xml_dataframe)

In [5]:
def load_data_to_duckdb(db_path, src_folder):
    data_dict = {
        "Date.txt": "wh_db.DimDate",
        "Time.txt": "wh_db.DimTime",
        "StatusType.txt": "wh_db.StatusType",
        "TaxRate.txt": "wh_db.TaxRate",
        "TradeType.txt": "wh_db.TradeType",
        "HR.csv": "temp_broker", #wh_db moved out to take into account SK_ID
        "Industry.txt": "wh_db.industry"
        # "FinwireCMP.txt": "wh_db.DimCompany"
    }
    
    con = duckdb.connect(database=db_path)
    
    for file_name, table_name in data_dict.items():
        file_path = os.path.join(src_folder, file_name)
        
        if file_name == "HR.csv":
            query = f"""
                CREATE OR REPLACE TABLE {table_name} AS 
                SELECT * FROM read_csv('{file_path}', delim=',', columns={{
                    'employeeid': 'BIGINT',
                    'managerid': 'BIGINT',
                    'employeefirstname': 'STRING',
                    'employeelastname': 'STRING',
                    'employeemi': 'STRING',
                    'employeejobcode': 'STRING',
                    'employeebranch': 'STRING',
                    'employeeoffice': 'STRING',
                    'employeephone': 'STRING'
                }}, header=False) 
                WHERE employeejobcode = '314';
            """

            insert_target_query = f"""
                INSERT INTO wh_db.DimBroker
                SELECT 
                    employeeid sk_brokerid,
                    employeeid brokerid,
                    managerid,
                    employeefirstname firstname,
                    employeelastname lastname,
                    employeemi middleinitial,
                    employeebranch branch,
                    employeeoffice office,
                    employeephone phone,
                    true iscurrent,
                    1 batchid, --temp, later read from db
                    (SELECT min(datevalue::DATE) as effectivedate FROM wh_db.DimDate) effectivedate,
                    '9999-12-31'::DATE enddate
                    FROM temp_broker;
                """
        else:
            query = f"COPY {table_name} FROM '{file_path}' (DELIMITER '|');"

        con.sql(query)
        save_sql_to_file(query, table_name)
        if file_name == "HR.csv":
            con.sql(insert_target_query)
            save_sql_to_file(insert_target_query, "wh_db.DimBroker")
        print(f"Loaded {file_name} into {table_name}")
        print(file_path)
    
    return con

# Example usage:
db_path = 'initial_db.duckdb'
src_folder = 'src/data/Batch1'
con = load_data_to_duckdb(db_path, src_folder)

# Test loading
#print(con.sql("SELECT * FROM wh_db.DimTime limit 10").fetchdf(10))

Loaded Date.txt into wh_db.DimDate
src/data/Batch1\Date.txt
Loaded Time.txt into wh_db.DimTime
src/data/Batch1\Time.txt
Loaded StatusType.txt into wh_db.StatusType
src/data/Batch1\StatusType.txt
Loaded TaxRate.txt into wh_db.TaxRate
src/data/Batch1\TaxRate.txt
Loaded TradeType.txt into wh_db.TradeType
src/data/Batch1\TradeType.txt
Loaded HR.csv into temp_broker
src/data/Batch1\HR.csv
Loaded Industry.txt into wh_db.industry
src/data/Batch1\Industry.txt

In [6]:
insert_target_query = f"""
                INSERT INTO wh_db.DimBroker
                SELECT 
                    employeeid sk_brokerid,
                    employeeid brokerid,
                    managerid,
                    employeefirstname firstname,
                    employeelastname lastname,
                    employeemi middleinitial,
                    employeebranch branch,
                    employeeoffice office,
                    employeephone phone,
                    true iscurrent,
                    1 batchid, --temp, later read from db
                    (SELECT min(datevalue::DATE) as effectivedate FROM wh_db.DimDate) effectivedate,
                    '9999-12-31'::DATE enddate
                    FROM temp_broker;
                """

con_path = r"initial_db.duckdb"
con = duckdb.connect(con_path)
save_sql_to_file(insert_target_query, "wh_db.DimBroker")

In [4]:
con_path = r"initial_db.duckdb"
con = duckdb.connect(con_path)

In [6]:
print(con.execute("select COLUMN_COMMENT from information_schema.columns where table_name = 'DimBroker' limit 1").fetchdf())

             COLUMN_COMMENT
0  Surrogate key for broker

In [ ]:
def get_table_schema(db_path, table_name):
    query = f"""
        SELECT 
            column_name AS name, 
            data_type AS type, 
            COLUMN_COMMENT AS description
        FROM information_schema.columns
        WHERE table_name = '{table_name}'
    """

    con = duckdb.connect(database=db_path)
    result = con.sql(query).fetchall()

    # Format result into the required structure
    schema_columns = [
        {"name": row[0], "type": row[1], "description": row[2] if row[2] else ""}
        for row in result
    ]

    return result

# Example usage

db_path = 'initial_db.duckdb'
table_name = 'DimBroker'
schema_columns = get_table_schema(db_path, table_name)

print(schema_columns)

[('sk_brokerid', 'BIGINT', 'Surrogate key for broker'), ('brokerid', 'BIGINT', 'Natural key for broker'), ('managerid', 'BIGINT', 'Natural key for managerâ€™s HR record'), ('firstname', 'VARCHAR', 'First name'), ('lastname', 'VARCHAR', 'Last Name'), ('middleinitial', 'VARCHAR', 'Middle initial'), ('branch', 'VARCHAR', 'Facility in which employee has office'), ('office', 'VARCHAR', 'Office number or description'), ('phone', 'VARCHAR', 'Employee phone number'), ('iscurrent', 'BOOLEAN', 'True if this is the current record'), ('batchid', 'INTEGER', 'Batch ID when this record was inserted'), ('effectivedate', 'DATE', 'Beginning of date range when this record was the current record'), ('enddate', 'DATE', 'Ending of date range when this record was the current record. A record that is not expired will use the date 9999-12-31.')]

In [7]:
stage_CustomerMgmt = """ 
        CREATE OR REPLACE TABLE wh_db_stage.CustomerMgmt  AS  
        SELECT
        try_cast(C_ID as BIGINT) customerid,
        try_cast(CA_ID as BIGINT) accountid,
        try_cast(CA_B_ID as BIGINT) brokerid,
        nullif(C_TAX_ID, '') taxid,
        nullif(CA_NAME, '') accountdesc,
        try_cast(CA_TAX_ST as TINYINT) taxstatus,
        CASE
            WHEN ActionType IN ('NEW', 'ADDACCT', 'UPDACCT', 'UPDCUST') THEN 'Active'
            WHEN ActionType IN ('CLOSEACCT', 'INACT') THEN 'Inactive'
            ELSE NULL
        END AS status,
        nullif(C_L_NAME, '') lastname,
        nullif(C_F_NAME, '') firstname,
        nullif(C_M_NAME, '') middleinitial,
        nullif(upper(C_GNDR), '') gender,
        try_cast(C_TIER as TINYINT) tier,
        try_cast(C_DOB as DATE) dob,
        nullif(C_ADLINE1, '') addressline1,
        nullif(C_ADLINE2, '') addressline2,
        nullif(C_ZIPCODE, '') postalcode,
        nullif(C_CITY, '') city,
        nullif(C_STATE_PROV, '') stateprov,
        nullif(C_CTRY, '') country,
        CASE
            WHEN nullif(C_LOCAL, '') IS NOT NULL THEN
                concat(
                    CASE WHEN nullif(C_CTRY_CODE, '') IS NOT NULL THEN '+' || C_CTRY_CODE || ' ' ELSE '' END,
                    CASE WHEN nullif(C_AREA_CODE, '') IS NOT NULL THEN '(' || C_AREA_CODE || ') ' ELSE '' END,
                    C_LOCAL,
                    COALESCE(C_EXT, '')
                )
            ELSE NULL
        END AS phone1,
        CASE
            WHEN nullif(C_LOCAL_1, '') IS NOT NULL THEN
                concat(
                    CASE WHEN nullif(C_CTRY_CODE_1, '') IS NOT NULL THEN '+' || C_CTRY_CODE_1 || ' ' ELSE '' END,
                    CASE WHEN nullif(C_AREA_CODE_1, '') IS NOT NULL THEN '(' || C_AREA_CODE_1 || ') ' ELSE '' END,
                    C_LOCAL_1,
                    COALESCE(C_EXT_1, '')
                )
            ELSE NULL
        END AS phone2,
        CASE
            WHEN nullif(C_LOCAL_2, '') IS NOT NULL THEN
                concat(
                    CASE WHEN nullif(C_CTRY_CODE_2, '') IS NOT NULL THEN '+' || C_CTRY_CODE_2 || ' ' ELSE '' END,
                    CASE WHEN nullif(C_AREA_CODE_2, '') IS NOT NULL THEN '(' || C_AREA_CODE_2 || ') ' ELSE '' END,
                    C_LOCAL_2,
                    COALESCE(C_EXT_2, '')
                )
            ELSE NULL
        END AS phone3,
        nullif(C_PRIM_EMAIL, '') email1,
        nullif(C_ALT_EMAIL, '') email2,
        nullif(C_LCL_TX_ID, '') lcl_tx_id,
        nullif(C_NAT_TX_ID, '') nat_tx_id,
        try_cast(ActionTS as TIMESTAMP) update_ts,
        ActionType
           
            FROM xml_dataframe"""

con.sql(stage_CustomerMgmt)
#save_sql_to_file(insert_target_query, "wh_db_stage.CustomerMgmt")

In [8]:
save_sql_to_file(insert_target_query, "wh_db.DimBroker")

In [9]:
import os
import re

def find_finwire_files(folder_path):
    """
    Traverses a folder recursively and finds files matching the pattern
    FINWIRE<YYYY>Q<Q> (e.g., FINWIRE2016Q3, FINWIRE2016Q4.txt).

    It specifically looks for filenames where the part *before* the extension
    exactly matches the pattern 'FINWIRE' followed by 4 digits (year),
    'Q', and 1 digit (quarter). Files with additional suffixes before the
    extension (like '_audit' in FINWIRE1967Q2_audit.csv) are skipped.

    Args:
        folder_path (str): The path to the folder to traverse.

    Returns:
        list: A list of full paths to the matching files.
               Returns an empty list if the folder doesn't exist or no
               matching files are found.
    """
    matching_files = []

    # Regex pattern:
    # ^        - anchor to the start of the string
    # FINWIRE  - literal string
    # \d{4}    - exactly 4 digits (for the year)
    # Q        - literal character 'Q'
    # \d       - exactly 1 digit (for the quarter)
    # $        - anchor to the end of the string
    # This pattern ensures the base name matches exactly.
    pattern = re.compile(r"^FINWIRE\d{4}Q\d$")

    # Check if the folder path exists
    if not os.path.isdir(folder_path):
        print(f"Warning: Folder not found at {folder_path}")
        return matching_files

    # os.walk traverses the directory tree (root, dirs, files)
    for root, _, files in os.walk(folder_path):
        for filename in files:
            # Split the filename into the base name and the extension
            base_name, _ = os.path.splitext(filename)

            # Check if the base name matches the compiled regex pattern
            if pattern.match(base_name):
                # If it matches, construct the full path and add it to the list
                full_path = os.path.join(root, filename)
                matching_files.append(full_path)

    return matching_files

find_finwire_files(src_folder)

['src/data/Batch1\\FINWIRE1967Q1',
 'src/data/Batch1\\FINWIRE1967Q2',
 'src/data/Batch1\\FINWIRE1967Q3',
 'src/data/Batch1\\FINWIRE1967Q4',
 'src/data/Batch1\\FINWIRE1968Q1',
 'src/data/Batch1\\FINWIRE1968Q2',
 'src/data/Batch1\\FINWIRE1968Q3',
 'src/data/Batch1\\FINWIRE1968Q4',
 'src/data/Batch1\\FINWIRE1969Q1',
 'src/data/Batch1\\FINWIRE1969Q2',
 'src/data/Batch1\\FINWIRE1969Q3',
 'src/data/Batch1\\FINWIRE1969Q4',
 'src/data/Batch1\\FINWIRE1970Q1',
 'src/data/Batch1\\FINWIRE1970Q2',
 'src/data/Batch1\\FINWIRE1970Q3',
 'src/data/Batch1\\FINWIRE1970Q4',
 'src/data/Batch1\\FINWIRE1971Q1',
 'src/data/Batch1\\FINWIRE1971Q2',
 'src/data/Batch1\\FINWIRE1971Q3',
 'src/data/Batch1\\FINWIRE1971Q4',
 'src/data/Batch1\\FINWIRE1972Q1',
 'src/data/Batch1\\FINWIRE1972Q2',
 'src/data/Batch1\\FINWIRE1972Q3',
 'src/data/Batch1\\FINWIRE1972Q4',
 'src/data/Batch1\\FINWIRE1973Q1',
 'src/data/Batch1\\FINWIRE1973Q2',
 'src/data/Batch1\\FINWIRE1973Q3',
 'src/data/Batch1\\FINWIRE1973Q4',
 'src/data/Batch1\\FINWIRE1974Q1',
 'src/data/Batch1\\FINWIRE1974Q2',
 'src/data/Batch1\\FINWIRE1974Q3',
 'src/data/Batch1\\FINWIRE1974Q4',
 'src/data/Batch1\\FINWIRE1975Q1',
 'src/data/Batch1\\FINWIRE1975Q2',
 'src/data/Batch1\\FINWIRE1975Q3',
 'src/data/Batch1\\FINWIRE1975Q4',
 'src/data/Batch1\\FINWIRE1976Q1',
 'src/data/Batch1\\FINWIRE1976Q2',
 'src/data/Batch1\\FINWIRE1976Q3',
 'src/data/Batch1\\FINWIRE1976Q4',
 'src/data/Batch1\\FINWIRE1977Q1',
 'src/data/Batch1\\FINWIRE1977Q2',
 'src/data/Batch1\\FINWIRE1977Q3',
 'src/data/Batch1\\FINWIRE1977Q4',
 'src/data/Batch1\\FINWIRE1978Q1',
 'src/data/Batch1\\FINWIRE1978Q2',
 'src/data/Batch1\\FINWIRE1978Q3',
 'src/data/Batch1\\FINWIRE1978Q4',
 'src/data/Batch1\\FINWIRE1979Q1',
 'src/data/Batch1\\FINWIRE1979Q2',
 'src/data/Batch1\\FINWIRE1979Q3',
 'src/data/Batch1\\FINWIRE1979Q4',
 'src/data/Batch1\\FINWIRE1980Q1',
 'src/data/Batch1\\FINWIRE1980Q2',
 'src/data/Batch1\\FINWIRE1980Q3',
 'src/data/Batch1\\FINWIRE1980Q4',
 'src/data/Batch1\\FINWIRE1981Q1',
 'src/data/Batch1\\FINWIRE1981Q2',
 'src/data/Batch1\\FINWIRE1981Q3',
 'src/data/Batch1\\FINWIRE1981Q4',
 'src/data/Batch1\\FINWIRE1982Q1',
 'src/data/Batch1\\FINWIRE1982Q2',
 'src/data/Batch1\\FINWIRE1982Q3',
 'src/data/Batch1\\FINWIRE1982Q4',
 'src/data/Batch1\\FINWIRE1983Q1',
 'src/data/Batch1\\FINWIRE1983Q2',
 'src/data/Batch1\\FINWIRE1983Q3',
 'src/data/Batch1\\FINWIRE1983Q4',
 'src/data/Batch1\\FINWIRE1984Q1',
 'src/data/Batch1\\FINWIRE1984Q2',
 'src/data/Batch1\\FINWIRE1984Q3',
 'src/data/Batch1\\FINWIRE1984Q4',
 'src/data/Batch1\\FINWIRE1985Q1',
 'src/data/Batch1\\FINWIRE1985Q2',
 'src/data/Batch1\\FINWIRE1985Q3',
 'src/data/Batch1\\FINWIRE1985Q4',
 'src/data/Batch1\\FINWIRE1986Q1',
 'src/data/Batch1\\FINWIRE1986Q2',
 'src/data/Batch1\\FINWIRE1986Q3',
 'src/data/Batch1\\FINWIRE1986Q4',
 'src/data/Batch1\\FINWIRE1987Q1',
 'src/data/Batch1\\FINWIRE1987Q2',
 'src/data/Batch1\\FINWIRE1987Q3',
 'src/data/Batch1\\FINWIRE1987Q4',
 'src/data/Batch1\\FINWIRE1988Q1',
 'src/data/Batch1\\FINWIRE1988Q2',
 'src/data/Batch1\\FINWIRE1988Q3',
 'src/data/Batch1\\FINWIRE1988Q4',
 'src/data/Batch1\\FINWIRE1989Q1',
 'src/data/Batch1\\FINWIRE1989Q2',
 'src/data/Batch1\\FINWIRE1989Q3',
 'src/data/Batch1\\FINWIRE1989Q4',
 'src/data/Batch1\\FINWIRE1990Q1',
 'src/data/Batch1\\FINWIRE1990Q2',
 'src/data/Batch1\\FINWIRE1990Q3',
 'src/data/Batch1\\FINWIRE1990Q4',
 'src/data/Batch1\\FINWIRE1991Q1',
 'src/data/Batch1\\FINWIRE1991Q2',
 'src/data/Batch1\\FINWIRE1991Q3',
 'src/data/Batch1\\FINWIRE1991Q4',
 'src/data/Batch1\\FINWIRE1992Q1',
 'src/data/Batch1\\FINWIRE1992Q2',
 'src/data/Batch1\\FINWIRE1992Q3',
 'src/data/Batch1\\FINWIRE1992Q4',
 'src/data/Batch1\\FINWIRE1993Q1',
 'src/data/Batch1\\FINWIRE1993Q2',
 'src/data/Batch1\\FINWIRE1993Q3',
 'src/data/Batch1\\FINWIRE1993Q4',
 'src/data/Batch1\\FINWIRE1994Q1',
 'src/data/Batch1\\FINWIRE1994Q2',
 'src/data/Batch1\\FINWIRE1994Q3',
 'src/data/Batch1\\FINWIRE1994Q4',
 'src/data/Batch1\\FINWIRE1995Q1',
 'src/data/Batch1\\FINWIRE1995Q2',
 'src/data/Batch1\\FINWIRE1995Q3',
 'src/data/Batch1\\FINWIRE1995Q4',
 'src/data/Batch1\\FINWIRE1996Q1',
 'src/data/Batch1\\FINWIRE1996Q2',
 'src/data/Batch1\\FINWIRE1996Q3',
 'src/data/Batch1\\FINWIRE1996Q4',
 'src/data/Batch1\\FINWIRE1997Q1',
 'src/data/Batch1\\FINWIRE1997Q2',
 'src/data/Batch1\\FINWIRE1997Q3',
 'src/data/Batch1\\FINWIRE1997Q4',
 'src/data/Batch1\\FINWIRE1998Q1',
 'src/data/Batch1\\FINWIRE1998Q2',
 'src/data/Batch1\\FINWIRE1998Q3',
 'src/data/Batch1\\FINWIRE1998Q4',
 'src/data/Batch1\\FINWIRE1999Q1',
 'src/data/Batch1\\FINWIRE1999Q2',
 'src/data/Batch1\\FINWIRE1999Q3',
 'src/data/Batch1\\FINWIRE1999Q4',
 'src/data/Batch1\\FINWIRE2000Q1',
 'src/data/Batch1\\FINWIRE2000Q2',
 'src/data/Batch1\\FINWIRE2000Q3',
 'src/data/Batch1\\FINWIRE2000Q4',
 'src/data/Batch1\\FINWIRE2001Q1',
 'src/data/Batch1\\FINWIRE2001Q2',
 'src/data/Batch1\\FINWIRE2001Q3',
 'src/data/Batch1\\FINWIRE2001Q4',
 'src/data/Batch1\\FINWIRE2002Q1',
 'src/data/Batch1\\FINWIRE2002Q2',
 'src/data/Batch1\\FINWIRE2002Q3',
 'src/data/Batch1\\FINWIRE2002Q4',
 'src/data/Batch1\\FINWIRE2003Q1',
 'src/data/Batch1\\FINWIRE2003Q2',
 'src/data/Batch1\\FINWIRE2003Q3',
 'src/data/Batch1\\FINWIRE2003Q4',
 'src/data/Batch1\\FINWIRE2004Q1',
 'src/data/Batch1\\FINWIRE2004Q2',
 'src/data/Batch1\\FINWIRE2004Q3',
 'src/data/Batch1\\FINWIRE2004Q4',
 'src/data/Batch1\\FINWIRE2005Q1',
 'src/data/Batch1\\FINWIRE2005Q2',
 'src/data/Batch1\\FINWIRE2005Q3',
 'src/data/Batch1\\FINWIRE2005Q4',
 'src/data/Batch1\\FINWIRE2006Q1',
 'src/data/Batch1\\FINWIRE2006Q2',
 'src/data/Batch1\\FINWIRE2006Q3',
 'src/data/Batch1\\FINWIRE2006Q4',
 'src/data/Batch1\\FINWIRE2007Q1',
 'src/data/Batch1\\FINWIRE2007Q2',
 'src/data/Batch1\\FINWIRE2007Q3',
 'src/data/Batch1\\FINWIRE2007Q4',
 'src/data/Batch1\\FINWIRE2008Q1',
 'src/data/Batch1\\FINWIRE2008Q2',
 'src/data/Batch1\\FINWIRE2008Q3',
 'src/data/Batch1\\FINWIRE2008Q4',
 'src/data/Batch1\\FINWIRE2009Q1',
 'src/data/Batch1\\FINWIRE2009Q2',
 'src/data/Batch1\\FINWIRE2009Q3',
 'src/data/Batch1\\FINWIRE2009Q4',
 'src/data/Batch1\\FINWIRE2010Q1',
 'src/data/Batch1\\FINWIRE2010Q2',
 'src/data/Batch1\\FINWIRE2010Q3',
 'src/data/Batch1\\FINWIRE2010Q4',
 'src/data/Batch1\\FINWIRE2011Q1',
 'src/data/Batch1\\FINWIRE2011Q2',
 'src/data/Batch1\\FINWIRE2011Q3',
 'src/data/Batch1\\FINWIRE2011Q4',
 'src/data/Batch1\\FINWIRE2012Q1',
 'src/data/Batch1\\FINWIRE2012Q2',
 'src/data/Batch1\\FINWIRE2012Q3',
 'src/data/Batch1\\FINWIRE2012Q4',
 'src/data/Batch1\\FINWIRE2013Q1',
 'src/data/Batch1\\FINWIRE2013Q2',
 'src/data/Batch1\\FINWIRE2013Q3',
 'src/data/Batch1\\FINWIRE2013Q4',
 'src/data/Batch1\\FINWIRE2014Q1',
 'src/data/Batch1\\FINWIRE2014Q2',
 'src/data/Batch1\\FINWIRE2014Q3',
 'src/data/Batch1\\FINWIRE2014Q4',
 'src/data/Batch1\\FINWIRE2015Q1',
 'src/data/Batch1\\FINWIRE2015Q2',
 'src/data/Batch1\\FINWIRE2015Q3',
 'src/data/Batch1\\FINWIRE2015Q4',
 'src/data/Batch1\\FINWIRE2016Q1',
 'src/data/Batch1\\FINWIRE2016Q2',
 'src/data/Batch1\\FINWIRE2016Q3',
 'src/data/Batch1\\FINWIRE2016Q4',
 'src/data/Batch1\\FINWIRE2017Q1',
 'src/data/Batch1\\FINWIRE2017Q2',
 'src/data/Batch1\\FINWIRE2017Q3']

In [ ]:
# siin pooleli

src_folder = 'src/data/Batch1'
list_of_finwire_files = find_finwire_files(src_folder)
# file_path = os.path.join(src_folder, "FINWIRE2016Q3")


fin_wire_sql = f""" 
    INSERT INTO wh_db_stage.FinWire
    SELECT
        CASE
            WHEN SUBSTR(column0, 16, 3) = 'FIN' THEN
                CASE
                    WHEN TRY_CAST(TRIM(SUBSTR(column0, 187, 60)) AS BIGINT) IS NOT NULL THEN 'FIN_COMPANYID'
                    ELSE 'FIN_NAME'
                END
            ELSE SUBSTR(column0, 16, 3)
        END AS rectype,
        STRPTIME(SUBSTR(column0, 1, 8), '%Y%m%d') AS recdate,
        SUBSTR(column0, 19) AS value
    FROM read_csv_auto('{file_path}', HEADER=FALSE, filename=false, all_varchar=true)
    """

for file_path in list_of_finwire_files:
    #file_path = os.path.join(src_folder, file)
    # õige
    con.sql(fin_wire_sql)
    save_sql_to_file(fin_wire_sql, "wh_db_stage.FinWire")
    print(file_path, "--DONE--")

src/data/Batch1\FINWIRE1967Q1 --DONE--
src/data/Batch1\FINWIRE1967Q2 --DONE--
src/data/Batch1\FINWIRE1967Q3 --DONE--
src/data/Batch1\FINWIRE1967Q4 --DONE--
src/data/Batch1\FINWIRE1968Q1 --DONE--
src/data/Batch1\FINWIRE1968Q2 --DONE--
src/data/Batch1\FINWIRE1968Q3 --DONE--
src/data/Batch1\FINWIRE1968Q4 --DONE--
src/data/Batch1\FINWIRE1969Q1 --DONE--
src/data/Batch1\FINWIRE1969Q2 --DONE--
src/data/Batch1\FINWIRE1969Q3 --DONE--
src/data/Batch1\FINWIRE1969Q4 --DONE--
src/data/Batch1\FINWIRE1970Q1 --DONE--
src/data/Batch1\FINWIRE1970Q2 --DONE--
src/data/Batch1\FINWIRE1970Q3 --DONE--
src/data/Batch1\FINWIRE1970Q4 --DONE--
src/data/Batch1\FINWIRE1971Q1 --DONE--
src/data/Batch1\FINWIRE1971Q2 --DONE--
src/data/Batch1\FINWIRE1971Q3 --DONE--
src/data/Batch1\FINWIRE1971Q4 --DONE--
src/data/Batch1\FINWIRE1972Q1 --DONE--
src/data/Batch1\FINWIRE1972Q2 --DONE--
src/data/Batch1\FINWIRE1972Q3 --DONE--
src/data/Batch1\FINWIRE1972Q4 --DONE--
src/data/Batch1\FINWIRE1973Q1 --DONE--
src/data/Batch1\FINWIRE1973Q2 --DONE--
src/data/Batch1\FINWIRE1973Q3 --DONE--
src/data/Batch1\FINWIRE1973Q4 --DONE--
src/data/Batch1\FINWIRE1974Q1 --DONE--
src/data/Batch1\FINWIRE1974Q2 --DONE--
src/data/Batch1\FINWIRE1974Q3 --DONE--
src/data/Batch1\FINWIRE1974Q4 --DONE--
src/data/Batch1\FINWIRE1975Q1 --DONE--
src/data/Batch1\FINWIRE1975Q2 --DONE--
src/data/Batch1\FINWIRE1975Q3 --DONE--
src/data/Batch1\FINWIRE1975Q4 --DONE--
src/data/Batch1\FINWIRE1976Q1 --DONE--
src/data/Batch1\FINWIRE1976Q2 --DONE--
src/data/Batch1\FINWIRE1976Q3 --DONE--
src/data/Batch1\FINWIRE1976Q4 --DONE--
src/data/Batch1\FINWIRE1977Q1 --DONE--
src/data/Batch1\FINWIRE1977Q2 --DONE--
src/data/Batch1\FINWIRE1977Q3 --DONE--
src/data/Batch1\FINWIRE1977Q4 --DONE--
src/data/Batch1\FINWIRE1978Q1 --DONE--
src/data/Batch1\FINWIRE1978Q2 --DONE--
src/data/Batch1\FINWIRE1978Q3 --DONE--
src/data/Batch1\FINWIRE1978Q4 --DONE--
src/data/Batch1\FINWIRE1979Q1 --DONE--
src/data/Batch1\FINWIRE1979Q2 --DONE--
src/data/Batch1\FINWIRE1979Q3 --DONE--
src/data/Batch1\FINWIRE1979Q4 --DONE--
src/data/Batch1\FINWIRE1980Q1 --DONE--
src/data/Batch1\FINWIRE1980Q2 --DONE--
src/data/Batch1\FINWIRE1980Q3 --DONE--
src/data/Batch1\FINWIRE1980Q4 --DONE--
src/data/Batch1\FINWIRE1981Q1 --DONE--
src/data/Batch1\FINWIRE1981Q2 --DONE--
src/data/Batch1\FINWIRE1981Q3 --DONE--
src/data/Batch1\FINWIRE1981Q4 --DONE--
src/data/Batch1\FINWIRE1982Q1 --DONE--
src/data/Batch1\FINWIRE1982Q2 --DONE--
src/data/Batch1\FINWIRE1982Q3 --DONE--
src/data/Batch1\FINWIRE1982Q4 --DONE--
src/data/Batch1\FINWIRE1983Q1 --DONE--
src/data/Batch1\FINWIRE1983Q2 --DONE--
src/data/Batch1\FINWIRE1983Q3 --DONE--
src/data/Batch1\FINWIRE1983Q4 --DONE--
src/data/Batch1\FINWIRE1984Q1 --DONE--
src/data/Batch1\FINWIRE1984Q2 --DONE--
src/data/Batch1\FINWIRE1984Q3 --DONE--
src/data/Batch1\FINWIRE1984Q4 --DONE--
src/data/Batch1\FINWIRE1985Q1 --DONE--
src/data/Batch1\FINWIRE1985Q2 --DONE--
src/data/Batch1\FINWIRE1985Q3 --DONE--
src/data/Batch1\FINWIRE1985Q4 --DONE--
src/data/Batch1\FINWIRE1986Q1 --DONE--
src/data/Batch1\FINWIRE1986Q2 --DONE--
src/data/Batch1\FINWIRE1986Q3 --DONE--
src/data/Batch1\FINWIRE1986Q4 --DONE--
src/data/Batch1\FINWIRE1987Q1 --DONE--
src/data/Batch1\FINWIRE1987Q2 --DONE--
src/data/Batch1\FINWIRE1987Q3 --DONE--
src/data/Batch1\FINWIRE1987Q4 --DONE--
src/data/Batch1\FINWIRE1988Q1 --DONE--
src/data/Batch1\FINWIRE1988Q2 --DONE--
src/data/Batch1\FINWIRE1988Q3 --DONE--
src/data/Batch1\FINWIRE1988Q4 --DONE--
src/data/Batch1\FINWIRE1989Q1 --DONE--
src/data/Batch1\FINWIRE1989Q2 --DONE--
src/data/Batch1\FINWIRE1989Q3 --DONE--
src/data/Batch1\FINWIRE1989Q4 --DONE--
src/data/Batch1\FINWIRE1990Q1 --DONE--
src/data/Batch1\FINWIRE1990Q2 --DONE--
src/data/Batch1\FINWIRE1990Q3 --DONE--
src/data/Batch1\FINWIRE1990Q4 --DONE--
src/data/Batch1\FINWIRE1991Q1 --DONE--
src/data/Batch1\FINWIRE1991Q2 --DONE--
src/data/Batch1\FINWIRE1991Q3 --DONE--
src/data/Batch1\FINWIRE1991Q4 --DONE--
src/data/Batch1\FINWIRE1992Q1 --DONE--
src/data/Batch1\FINWIRE1992Q2 --DONE--
src/data/Batch1\FINWIRE1992Q3 --DONE--
src/data/Batch1\FINWIRE1992Q4 --DONE--
src/data/Batch1\FINWIRE1993Q1 --DONE--
src/data/Batch1\FINWIRE1993Q2 --DONE--
src/data/Batch1\FINWIRE1993Q3 --DONE--
src/data/Batch1\FINWIRE1993Q4 --DONE--
src/data/Batch1\FINWIRE1994Q1 --DONE--
src/data/Batch1\FINWIRE1994Q2 --DONE--
src/data/Batch1\FINWIRE1994Q3 --DONE--
src/data/Batch1\FINWIRE1994Q4 --DONE--
src/data/Batch1\FINWIRE1995Q1 --DONE--
src/data/Batch1\FINWIRE1995Q2 --DONE--
src/data/Batch1\FINWIRE1995Q3 --DONE--
src/data/Batch1\FINWIRE1995Q4 --DONE--
src/data/Batch1\FINWIRE1996Q1 --DONE--
src/data/Batch1\FINWIRE1996Q2 --DONE--
src/data/Batch1\FINWIRE1996Q3 --DONE--
src/data/Batch1\FINWIRE1996Q4 --DONE--
src/data/Batch1\FINWIRE1997Q1 --DONE--
src/data/Batch1\FINWIRE1997Q2 --DONE--
src/data/Batch1\FINWIRE1997Q3 --DONE--
src/data/Batch1\FINWIRE1997Q4 --DONE--
src/data/Batch1\FINWIRE1998Q1 --DONE--
src/data/Batch1\FINWIRE1998Q2 --DONE--
src/data/Batch1\FINWIRE1998Q3 --DONE--
src/data/Batch1\FINWIRE1998Q4 --DONE--
src/data/Batch1\FINWIRE1999Q1 --DONE--
src/data/Batch1\FINWIRE1999Q2 --DONE--
src/data/Batch1\FINWIRE1999Q3 --DONE--
src/data/Batch1\FINWIRE1999Q4 --DONE--
src/data/Batch1\FINWIRE2000Q1 --DONE--
src/data/Batch1\FINWIRE2000Q2 --DONE--
src/data/Batch1\FINWIRE2000Q3 --DONE--
src/data/Batch1\FINWIRE2000Q4 --DONE--
src/data/Batch1\FINWIRE2001Q1 --DONE--
src/data/Batch1\FINWIRE2001Q2 --DONE--
src/data/Batch1\FINWIRE2001Q3 --DONE--
src/data/Batch1\FINWIRE2001Q4 --DONE--
src/data/Batch1\FINWIRE2002Q1 --DONE--
src/data/Batch1\FINWIRE2002Q2 --DONE--
src/data/Batch1\FINWIRE2002Q3 --DONE--
src/data/Batch1\FINWIRE2002Q4 --DONE--
src/data/Batch1\FINWIRE2003Q1 --DONE--
src/data/Batch1\FINWIRE2003Q2 --DONE--
src/data/Batch1\FINWIRE2003Q3 --DONE--
src/data/Batch1\FINWIRE2003Q4 --DONE--
src/data/Batch1\FINWIRE2004Q1 --DONE--
src/data/Batch1\FINWIRE2004Q2 --DONE--
src/data/Batch1\FINWIRE2004Q3 --DONE--
src/data/Batch1\FINWIRE2004Q4 --DONE--
src/data/Batch1\FINWIRE2005Q1 --DONE--
src/data/Batch1\FINWIRE2005Q2 --DONE--
src/data/Batch1\FINWIRE2005Q3 --DONE--
src/data/Batch1\FINWIRE2005Q4 --DONE--
src/data/Batch1\FINWIRE2006Q1 --DONE--
src/data/Batch1\FINWIRE2006Q2 --DONE--
src/data/Batch1\FINWIRE2006Q3 --DONE--
src/data/Batch1\FINWIRE2006Q4 --DONE--
src/data/Batch1\FINWIRE2007Q1 --DONE--
src/data/Batch1\FINWIRE2007Q2 --DONE--
src/data/Batch1\FINWIRE2007Q3 --DONE--
src/data/Batch1\FINWIRE2007Q4 --DONE--
src/data/Batch1\FINWIRE2008Q1 --DONE--
src/data/Batch1\FINWIRE2008Q2 --DONE--
src/data/Batch1\FINWIRE2008Q3 --DONE--
src/data/Batch1\FINWIRE2008Q4 --DONE--
src/data/Batch1\FINWIRE2009Q1 --DONE--
src/data/Batch1\FINWIRE2009Q2 --DONE--
src/data/Batch1\FINWIRE2009Q3 --DONE--
src/data/Batch1\FINWIRE2009Q4 --DONE--
src/data/Batch1\FINWIRE2010Q1 --DONE--
src/data/Batch1\FINWIRE2010Q2 --DONE--
src/data/Batch1\FINWIRE2010Q3 --DONE--
src/data/Batch1\FINWIRE2010Q4 --DONE--
src/data/Batch1\FINWIRE2011Q1 --DONE--
src/data/Batch1\FINWIRE2011Q2 --DONE--
src/data/Batch1\FINWIRE2011Q3 --DONE--
src/data/Batch1\FINWIRE2011Q4 --DONE--
src/data/Batch1\FINWIRE2012Q1 --DONE--
src/data/Batch1\FINWIRE2012Q2 --DONE--
src/data/Batch1\FINWIRE2012Q3 --DONE--
src/data/Batch1\FINWIRE2012Q4 --DONE--
src/data/Batch1\FINWIRE2013Q1 --DONE--
src/data/Batch1\FINWIRE2013Q2 --DONE--
src/data/Batch1\FINWIRE2013Q3 --DONE--
src/data/Batch1\FINWIRE2013Q4 --DONE--
src/data/Batch1\FINWIRE2014Q1 --DONE--
src/data/Batch1\FINWIRE2014Q2 --DONE--
src/data/Batch1\FINWIRE2014Q3 --DONE--
src/data/Batch1\FINWIRE2014Q4 --DONE--
src/data/Batch1\FINWIRE2015Q1 --DONE--
src/data/Batch1\FINWIRE2015Q2 --DONE--
src/data/Batch1\FINWIRE2015Q3 --DONE--
src/data/Batch1\FINWIRE2015Q4 --DONE--
src/data/Batch1\FINWIRE2016Q1 --DONE--
src/data/Batch1\FINWIRE2016Q2 --DONE--
src/data/Batch1\FINWIRE2016Q3 --DONE--
src/data/Batch1\FINWIRE2016Q4 --DONE--
src/data/Batch1\FINWIRE2017Q1 --DONE--
src/data/Batch1\FINWIRE2017Q2 --DONE--
src/data/Batch1\FINWIRE2017Q3 --DONE--

In [13]:
# õige
dimcompany_insert_sql = """INSERT INTO wh_db.DimCompany
WITH cmp AS (
    SELECT
        recdate,
        TRIM(SUBSTR(value, 1, 60)) AS CompanyName,
        TRIM(SUBSTR(value, 61, 10)) AS CIK,
        TRIM(SUBSTR(value, 71, 4)) AS Status,
        TRIM(SUBSTR(value, 75, 2)) AS IndustryID,
        TRIM(SUBSTR(value, 77, 4)) AS SPrating,
        TRY_CAST(TRY_CAST(SUBSTRING(value, 81, 8) AS TIMESTAMP) AS DATE) AS FoundingDate,
        TRIM(SUBSTR(value, 89, 80)) AS AddrLine1,
        TRIM(SUBSTR(value, 169, 80)) AS AddrLine2,
        TRIM(SUBSTR(value, 249, 12)) AS PostalCode,
        TRIM(SUBSTR(value, 261, 25)) AS City,
        TRIM(SUBSTR(value, 286, 20)) AS StateProvince,
        TRIM(SUBSTR(value, 306, 24)) AS Country,
        TRIM(SUBSTR(value, 330, 46)) AS CEOname,
        TRIM(SUBSTR(value, 376, 150)) AS Description
    FROM wh_db_stage.FinWire
    WHERE rectype = 'CMP'
)
SELECT
    CAST(strftime(effectivedate, '%Y%m%d') || companyid AS BIGINT) AS sk_companyid,
    companyid,
    status,
    name,
    industry,
    sprating,
    islowgrade,
    ceo,
    addressline1,
    addressline2,
    postalcode,
    city,
    stateprov,
    country,
    description,
    foundingdate,
    CASE WHEN enddate = '9999-12-31'::DATE THEN TRUE ELSE FALSE END AS iscurrent,
    batchid,
    effectivedate,
    enddate
FROM (
    SELECT
        CAST(cik AS BIGINT) AS companyid,
        CASE cmp.status
            WHEN 'ACTV' THEN 'Active'
            WHEN 'CMPT' THEN 'Completed'
            WHEN 'CNCL' THEN 'Canceled'
            WHEN 'PNDG' THEN 'Pending'
            WHEN 'SBMT' THEN 'Submitted'
            WHEN 'INAC' THEN 'Inactive'
            ELSE NULL -- or a default value, if needed
        END AS status,
        CompanyName AS name,
        ind.in_name AS industry,
        CASE
            WHEN SPrating IN ('AAA', 'AA', 'AA+', 'AA-', 'A', 'A+', 'A-', 'BBB', 'BBB+', 'BBB-', 'BB', 'BB+', 'BB-', 'B', 'B+', 'B-', 'CCC', 'CCC+', 'CCC-', 'CC', 'C', 'D') THEN SPrating
            ELSE NULL::VARCHAR
        END AS sprating,
        CASE
            WHEN SPrating IN ('AAA', 'AA', 'A', 'AA+', 'A+', 'AA-', 'A-', 'BBB', 'BBB+', 'BBB-') THEN FALSE
            WHEN SPrating IN ('BB', 'B', 'CCC', 'CC', 'C', 'D', 'BB+', 'B+', 'CCC+', 'BB-', 'B-', 'CCC-') THEN TRUE
            ELSE NULL::BOOLEAN
        END AS islowgrade,
        CEOname AS ceo,
        AddrLine1 AS addressline1,
        AddrLine2 AS addressline2,
        PostalCode AS postalcode,
        City AS city,
        StateProvince AS stateprov,
        Country AS country,
        Description AS description,
        FoundingDate AS foundingdate,
        1 AS batchid,
        recdate AS effectivedate,
        COALESCE(
            LEAD(try_cast(recdate AS DATE)) OVER (PARTITION BY cik ORDER BY recdate),
            try_cast('9999-12-31' AS DATE)
        ) AS enddate
    FROM cmp
    JOIN wh_db.industry ind ON cmp.industryid = ind.in_id
)
WHERE effectivedate < enddate;
"""

con.sql(dimcompany_insert_sql)
save_sql_to_file(dimcompany_insert_sql, "wh_db.DimCompany")

In [ ]:
src_folder = 'src/data/Batch1'
file_path = os.path.join(src_folder, "Prospect.csv")
batch_number = int(''.join(filter(str.isdigit, os.path.basename(src_folder))))

temp_propect = f"""
CREATE OR REPLACE TABLE temp_propect AS 
SELECT     *, 
    {batch_number} AS batchid 
    FROM read_csv_auto('{file_path}', columns={{
    "agencyid": "STRING",
    "lastname": "STRING",
    "firstname": "STRING",
    "middleinitial": "STRING",
    "gender": "STRING",
    "addressline1": "STRING",
    "addressline2": "STRING",
    "postalcode": "STRING",
    "city": "STRING",
    "state": "STRING",
    "country": "STRING",
    "phone": "STRING",
    "income": "INT",
    "numbercars": "INT",
    "numberchildren": "INT",
    "maritalstatus": "STRING",
    "age": "INT",
    "creditrating": "INT",
    "ownorrentflag": "STRING",
    "employer": "STRING",
    "numbercreditcards": "INT",
    "networth": "INT",
}}, header=False);
"""

con.execute(temp_propect).fetchall()
save_sql_to_file(temp_propect, "wh_db_stage.ProspectIncremental")

In [17]:
temp_propect_marketingnameplate = """
CREATE OR REPLACE TABLE temp_propect_marketingnameplate AS 
SELECT
    *,
    CASE 
        WHEN LENGTH(
            CONCAT(
                CASE WHEN networth > 1000000 OR income > 200000 THEN 'HighValue+' ELSE '' END,
                CASE WHEN numberchildren > 3 OR numbercreditcards > 5 THEN 'Expenses+' ELSE '' END,
                CASE WHEN age > 45 THEN 'Boomer+' ELSE '' END,
                CASE WHEN income < 50000 OR creditrating < 600 OR networth < 100000 THEN 'MoneyAlert+' ELSE '' END,
                CASE WHEN numbercars > 3 OR numbercreditcards > 7 THEN 'Spender+' ELSE '' END,
                CASE WHEN age < 25 AND networth > 1000000 THEN 'Inherited+' ELSE '' END
            )
        ) > 0 
        THEN LEFT(
            CONCAT(
                CASE WHEN networth > 1000000 OR income > 200000 THEN 'HighValue+' ELSE '' END,
                CASE WHEN numberchildren > 3 OR numbercreditcards > 5 THEN 'Expenses+' ELSE '' END,
                CASE WHEN age > 45 THEN 'Boomer+' ELSE '' END,
                CASE WHEN income < 50000 OR creditrating < 600 OR networth < 100000 THEN 'MoneyAlert+' ELSE '' END,
                CASE WHEN numbercars > 3 OR numbercreditcards > 7 THEN 'Spender+' ELSE '' END,
                CASE WHEN age < 25 AND networth > 1000000 THEN 'Inherited+' ELSE '' END
            ),
            LENGTH(
                CONCAT(
                    CASE WHEN networth > 1000000 OR income > 200000 THEN 'HighValue+' ELSE '' END,
                    CASE WHEN numberchildren > 3 OR numbercreditcards > 5 THEN 'Expenses+' ELSE '' END,
                    CASE WHEN age > 45 THEN 'Boomer+' ELSE '' END,
                    CASE WHEN income < 50000 OR creditrating < 600 OR networth < 100000 THEN 'MoneyAlert+' ELSE '' END,
                    CASE WHEN numbercars > 3 OR numbercreditcards > 7 THEN 'Spender+' ELSE '' END,
                    CASE WHEN age < 25 AND networth > 1000000 THEN 'Inherited+' ELSE '' END
                )
            ) - 1
        )
        ELSE NULL 
    END AS marketingnameplate
FROM temp_propect;
"""

con.sql(temp_propect_marketingnameplate)
save_sql_to_file(temp_propect_marketingnameplate, "wh_db_stage.ProspectIncremental")

In [10]:
## täpselt ei tea, mille järgi tuvastada ridu - st kas agency_id, firstname_lastname piisab
con.sql(""" 
ALTER TABLE wh_db_stage.ProspectIncremental
    ADD CONSTRAINT ProspectIncremental_pk PRIMARY KEY (agencyid, lastname, firstname);
""")

CatalogException: Catalog Error: an index with that name already exists for this table: PRIMARY_ProspectIncremental_agencyid_lastname_firstname

In [11]:
ProspectIncremental = """
INSERT INTO wh_db_stage.ProspectIncremental (
    agencyid, lastname, firstname, middleinitial, gender, addressline1, 
    addressline2, postalcode, city, state, country, phone, income, 
    numbercars, numberchildren, maritalstatus, age, creditrating, 
    ownorrentflag, employer, numbercreditcards, networth, 
    marketingnameplate, recordbatchid, batchid
)
SELECT
    tp.agencyid, tp.lastname, tp.firstname, tp.middleinitial, tp.gender, tp.addressline1, 
    tp.addressline2, tp.postalcode, tp.city, tp.state, tp.country, tp.phone, tp.income, 
    tp.numbercars, tp.numberchildren, tp.maritalstatus, tp.age, tp.creditrating, 
    tp.ownorrentflag, tp.employer, tp.numbercreditcards, tp.networth, 
    tp.marketingnameplate, tp.batchid, tp.batchid
FROM temp_propect_marketingnameplate AS tp
ON CONFLICT (agencyid, lastname, firstname) DO UPDATE SET
    middleinitial = excluded.middleinitial,
    gender = excluded.gender,
    addressline1 = excluded.addressline1,
    addressline2 = excluded.addressline2,
    postalcode = excluded.postalcode,
    city = excluded.city,
    state = excluded.state,
    country = excluded.country,
    phone = excluded.phone,
    income = excluded.income,
    numbercars = excluded.numbercars,
    numberchildren = excluded.numberchildren,
    maritalstatus = excluded.maritalstatus,
    age = excluded.age,
    creditrating = excluded.creditrating,
    ownorrentflag = excluded.ownorrentflag,
    employer = excluded.employer,
    numbercreditcards = excluded.numbercreditcards,
    networth = excluded.networth,
    marketingnameplate = excluded.marketingnameplate,
    recordbatchid = excluded.batchid;
"""
con.sql(ProspectIncremental)
save_sql_to_file(ProspectIncremental, "wh_db_stage.ProspectIncremental")

In [13]:
con.sql("select * from wh_db_stage.ProspectIncremental ")

┌──────────┬────────────────────────────────┬────────────────────────────────┬───────────────┬─────────┬───────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────┬──────────────┬─────────────────┬─────────┬──────────────────────────┬────────────────┬─────────┬────────────┬────────────────┬───────────────┬───────┬──────────────┬───────────────┬──────────────────────────┬───────────────────┬──────────┬─────────────────────────────────────────────────┬───────────────┬─────────┐
│ agencyid │            lastname            │           firstname            │ middleinitial │ gender  │                             addressline1                              │                              addressline2                               │  postalcode  │      city       │  state  │         country          │     phone      │ income  │ numbercars │ numberchildren │ maritalstatus │  age  │ creditrating │ ownorrentflag │         employer         │ numbercreditcards │ networth │               marketingnameplate                │ recordbatchid │ batchid │
│ varchar  │            varchar             │            varchar             │    varchar    │ varchar │                                varchar                                │                                 varchar                                 │   varchar    │     varchar     │ varchar │         varchar          │    varchar     │ varchar │   int32    │     int32      │    varchar    │ int32 │    int32     │    varchar    │         varchar          │       int32       │  int32   │                     varchar                     │     int32     │  int32  │
├──────────┼────────────────────────────────┼────────────────────────────────┼───────────────┼─────────┼───────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────┼──────────────┼─────────────────┼─────────┼──────────────────────────┼────────────────┼─────────┼────────────┼────────────────┼───────────────┼───────┼──────────────┼───────────────┼──────────────────────────┼───────────────────┼──────────┼─────────────────────────────────────────────────┼───────────────┼─────────┤
│ CLY0     │ CLYSDALE                       │ Leif                           │ NULL          │ m       │ 11538 kimberley boulevard                                             │ NULL                                                                    │ 97217        │ Chicago         │ FL      │ United States of America │ 1-712-522-6088 │ 368776  │       NULL │              3 │ W             │    20 │          760 │ O             │ Brink's                  │              NULL │  1058868 │ HighValue+Inherited                             │             1 │       1 │
│ NAN1     │ NANAMIYA                       │ CHARANGIT                      │ NULL          │ f       │ 13347 norwalk road                                                    │ NULL                                                                    │ 89506        │ Miami           │ NH      │ United States of America │ 1-626-426-4298 │ 177967  │          5 │              1 │ U             │     3 │          555 │ U             │ NULL                     │                 6 │  1988185 │ HighValue+Expenses+MoneyAlert+Spender+Inherited │             1 │       1 │
│ pea2     │ pearson                        │ pier                           │ NULL          │ F       │ 2134 neff south                                                       │ NULL                                                                    │ 35207        │ Des Moines      │ NY      │ United States of America │ 1-524-787-8784 │ 321772  │          2 │              1 │ S             │  NULL │          566 │ O             │ NULL                     │                 6 │  3673128 │ HighValue+Expenses+MoneyAlert                   │             1 │       1 │
│ PIL3     │ PILOTE                         │ Hazel                          │ NULL          │ NULL    │ 23923 potomac road                                                    │ NULL                                                                    │ t6d 1h9      │ Fayetteville    │ MO      │ Canada                   │ 1-741-997-1688 │ 25449   │          2 │              1 │ W             │    77 │         NULL │ O             │ Air Products & Chemicals │                 3 │  2005895 │ HighValue+Boomer+MoneyAlert                     │             1 │       1 │
│ DEN4     │ DENETTE                        │ kattie                         │ NULL          │ F       │ 21376 kirby lower                                                     │ NULL                                                                    │ 63172        │ Greensboro      │ NC      │ United States of America │ 1-002-194-1991 │ 166567  │          0 │              3 │ M             │    21 │          815 │ O             │ Oshkosh                  │                 4 │   624736 │ NULL                                            │             1 │       1 │
│ end5     │ endsley                        │ Deana                          │ E             │ f       │ 9993 kelvin park                                                      │ Apt. 177                                                                │ V6b 1r4      │ Salt Lake City  │ CA      │ United States of America │ 1-441-371-7651 │ 43631   │          1 │              4 │ M             │    77 │          333 │ R             │ NULL                     │                10 │  3064615 │ HighValue+Expenses+Boomer+MoneyAlert+Spender    │             1 │       1 │
│ Dun6     │ Dunham                         │ RIYAD                          │ NULL          │ NULL    │ 21448 HAMPTON BOULEVARD                                               │ NULL                                                                    │ 33158        │ Frederick       │ VT      │ United States of America │ 1-957-940-5980 │ 466230  │          4 │              0 │ NULL          │    23 │          528 │ O             │ VeraSun Energy           │                 1 │  3489129 │ HighValue+MoneyAlert+Spender+Inherited          │             1 │       1 │
│ Gow7     │ Gowan                          │ Riva                           │ X             │ M       │ 21620 snead avenue                                                    │ NULL                                                                    │ V6c 1p1      │ Santa Fe        │ OR      │ United States of America │ 1-768-633-4096 │ 420243  │          2 │              2 │ M             │     9 │          680 │ U             │ IDT                      │                 7 │  3430744 │ HighValue+Expenses+Inherited                    │             1 │       1 │
│ Nic8     │ Nickell                        │ Fina                           │ NULL          │ NULL    │ 19443 payne boulevard                                                 │ Suite 386                                                               │ 62705        │ Missoula        │ KS      │ United States of America │ 1-107-689-2155 │ 141862  │          3 │           NULL │ U             │    63 │          761 │ O             │ Adams Resources & Energy │                10 │  1743614 │ HighValue+Expenses+Boomer+Spender               │             1 │       1 │
│ Con9     │ Conrad                         │ birendra                       │ NULL          │ NULL    │ 14286 main boulevard                                                  │ NULL                                                                    │ 14230        │ Chandler        │ WA      │ United States of America │ 1-173-594-6096 │ 402011  │          0 │              2 │ M             │    32 │          416 │ O             │ MGIC Investment          │              NULL │   216299 │ HighValue+MoneyAlert                            │             1 │       1 │
│  ·       │   ·                            │    ·                           │ ·             │  ·      │      ·                                                                │  ·                                                                      │  ·           │    ·            │ ·       │            ·             │       ·        │   ·     │          · │              · │ ·             │     · │           ·  │ ·             │   ·                      │                 · │      ·   │     ·                                           │             · │       · │
│  ·       │   ·                            │    ·                           │ ·             │  ·      │      ·                                                                │  ·                                                                      │  ·           │    ·            │ ·       │            ·             │       ·        │   ·     │          · │              · │ ·             │     · │           ·  │ ·             │   ·                      │                 · │      ·   │     ·                                           │             · │       · │
│  ·       │   ·                            │    ·                           │ ·             │  ·      │      ·                                                                │  ·                                                                      │  ·           │    ·            │ ·       │            ·             │       ·        │   ·     │          · │              · │ ·             │     · │           ·  │ ·             │   ·                      │                 · │      ·   │     ·                                           │             · │       · │
│ Ohd10002 │ Ohdjoyrmhamjj                  │ wodnecilctbajrcwrbl            │ V             │ NULL    │ GWAXZQPIQGEL                                                          │ Luqwuvslojrxiujxuuatzngrrovlxnxqfkietycxcujcanymwowlizxgpymcmfyuraajos  │ NULL         │ Hartford        │ MD      │ United States of America │ 1-610-804-4891 │ 63385   │          1 │              1 │ U             │    41 │          428 │ O             │ Yahoo                    │                 3 │   407626 │ MoneyAlert                                      │             1 │       1 │
│ ovj10003 │ ovjslledhrxttcjem              │ Ovldwtd                        │ NULL          │ NULL    │ IBDCVCGTVOTETDUWYEJXIXWZRAIZCBUGXZZNJMZQBESAEAP                       │ Eudmiphfnkdxsfy                                                         │ Ipewrdvqnzwe │ Grand Rapids    │ WI      │ United States of America │ 1-675-268-0167 │ 234946  │          3 │              3 │ U             │    70 │          640 │ O             │ Ametek                   │                 7 │  2968167 │ HighValue+Expenses+Boomer                       │             1 │       1 │
│ Ogq10004 │ Ogqtggiu                       │ EQRNXKGSMCPKERM                │ NULL          │ NULL    │ Trkajapibwmnaijbebcxtzxtbddifvxvmuaohnirtdrochprkqqmgwhkfmn           │ Gtzvkqfwyqvbmjhyzlxuvrejnnpknwurjkjhqoukxncxjhboixkblskrlnqedwgvuncgzqk │ Jzamjampodn  │ Oakland         │ NV      │ United States of America │ 1-463-461-8590 │ 95378   │          4 │              2 │ S             │     0 │          340 │ U             │ Calpine                  │                 9 │  2655144 │ HighValue+Expenses+MoneyAlert+Spender+Inherited │             1 │       1 │
│ Nrd10005 │ Nrdrdxloqpvjegcjyt             │ Uegjsijczuzcndymzzpycbbaewoxby │ J             │ m       │ NICAKSTLUKTCJMOQIJZUMMKNVFSSOBQUNQDHLLQTLCBEDORXITJLWQIOCRHQNWMYP     │ Dvdhtouzbhfifgxzceoisloekbbuwefiasbtfufahhnmnjtlxkbjyiauwezze           │ gylhslmhw    │ Fairbanks       │ Ontario │ United States of America │ 1-807-997-8844 │ 379612  │          0 │              4 │ U             │    46 │          799 │ U             │ Universal                │                 5 │   608571 │ HighValue+Expenses+Boomer                       │             1 │       1 │
│ XRC10006 │ XRCOQFQANAJEAJRMMRBMLSLFYWAOTN │ Etesvpucqewtfwguftpanc         │ f             │ M       │ Svymhlworyzdhfwsjydegwwbrlajgyvqswowz                                 │ Sipdqqemvxdouqqpuchc                                                    │ Tcqkdbmfuqs  │ Fort Lauderdale │ ME      │ United States of America │ 1-072-522-9475 │ 81172   │          0 │              3 │ M             │    40 │          369 │ R             │ General Electric         │                10 │   653937 │ Expenses+MoneyAlert+Spender                     │             1 │       1 │
│ rto10007 │ rtomkzkywqadgbhzbuwkfcdgfeoqlm │ XULEMVBHEZFSVAMAAFC            │ NULL          │ f       │ Hhllepwvwxeikwxkdqtzocvnfleufsttflgnngeigwirqxrdfiaywjhtiabejkbqfdzez │ BNSCBBHLKJLYVXGMEEAPPIJWGWFFHM                                          │ BGMKKFDPX    │ Saint John      │ HI      │ United States of America │ 1-619-888-6726 │ 55966   │          4 │              0 │ M             │    82 │          424 │ O             │ Carlisle                 │              NULL │   747071 │ Boomer+MoneyAlert+Spender                       │             1 │       1 │
│ Mjx10008 │ Mjxbdobfsghzg                  │ Ortsnhe                        │ Q             │ NULL    │ Gzdaabwbuhgqiditihumaohop                                             │ Xyxtutiynrxki                                                           │ ukkxihipxw   │ Bismarck        │ ID      │ United States of America │ 1-447-246-4565 │ 207624  │          1 │              3 │ W             │    89 │          622 │ R             │ M&T Bank Corp.           │                 7 │  2835796 │ HighValue+Expenses+Boomer                       │             1 │       1 │
│ Jso10009 │ Jsoldzmaaheecdlgls             │ Rcutrnrsqcadqsji               │ x             │ F       │ rmvybnsrapehiibltgtimyvnhmvnsxhsqvstpmximaxsadvbcichkxkdjbdpsgunmwou  │ Xrdryzbcocgmqnkuofsamsmekjrlwbomhsnvsbnuryh                             │ TDDPKQ       │ Biloxi          │ SC      │ United States of America │ 1-841-673-0814 │ 424274  │          1 │              3 │ U             │     6 │          663 │ O             │ Service Enterprise Group │                10 │  3211023 │ HighValue+Expenses+Spender+Inherited            │             1 │       1 │
│ Crb10010 │ Crbawyvzncrxvyrxouwrvmizzg     │ Vpxoqiwevvlnus                 │ y             │ F       │ Ijoarzeztrfuojhxkpunxywjdc                                            │ zqcglgpkcfix                                                            │ Fkrxnjngzd   │ Torrance        │ OK      │ United States of America │ 1-615-225-4904 │ 56830   │       NULL │              4 │ M             │    86 │          383 │ O             │ Thrivent Financial       │                10 │  3143366 │ HighValue+Expenses+Boomer+MoneyAlert+Spender    │             1 │       1 │
│ tzh10011 │ tzhgqtbo                       │ Lhqiaepgiblszltvpfflgj         │ T             │ NULL    │ Cmguqwkrscsuvdldpxxdirtqboaqdwopq                                     │ ISSINBKGEBBMGWLAKQHJIQXJTCZBZDFUUKXQIZYTUIBS                            │ ovtuuwebxgnd │ Beaumont        │ CA      │ United States of America │ 1-688-763-9982 │ 406599  │          5 │           NULL │ W             │    70 │          353 │ O             │ Goodyear Tire & Rubber   │                 8 │  2870170 │ HighValue+Expenses+Boomer+MoneyAlert+Spender    │             1 │       1 │
├──────────┴────────────────────────────────┴────────────────────────────────┴───────────────┴─────────┴───────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────┴──────────────┴─────────────────┴─────────┴──────────────────────────┴────────────────┴─────────┴────────────┴────────────────┴───────────────┴───────┴──────────────┴───────────────┴──────────────────────────┴───────────────────┴──────────┴─────────────────────────────────────────────────┴───────────────┴─────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           25 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [32]:
con.sql(""" 
select distinct * from 
wh_db_stage.CustomerMgmt a
LEFT 
join wh_db.TaxRate b on
        a.nat_tx_id  = b.TX_ID
where a.customerid = 20
order by update_ts asc

""")

┌────────────┬───────────┬──────────┬─────────────┬───────────────────────────────────────────────┬───────────┬──────────┬──────────┬───────────┬───────────────┬─────────┬──────┬────────────┬──────────────────┬──────────────┬────────────┬───────────────┬───────────┬──────────────────────────┬────────────────┬──────────┬───────────────────┬───────────────────────────┬───────────────────────────────┬───────────┬───────────┬─────────────────────┬────────────┬─────────┬────────────────────────────────────────────┬─────────┐
│ customerid │ accountid │ brokerid │    taxid    │                  accountdesc                  │ taxstatus │  status  │ lastname │ firstname │ middleinitial │ gender  │ tier │    dob     │   addressline1   │ addressline2 │ postalcode │     city      │ stateprov │         country          │     phone1     │  phone2  │      phone3       │          email1           │            email2             │ lcl_tx_id │ nat_tx_id │      update_ts      │ ActionType │  tx_id  │                  tx_name                   │ tx_rate │
│   int64    │   int64   │  int64   │   varchar   │                    varchar                    │   int8    │ varchar  │ varchar  │  varchar  │    varchar    │ varchar │ int8 │    date    │     varchar      │   varchar    │  varchar   │    varchar    │  varchar  │         varchar          │    varchar     │ varchar  │      varchar      │          varchar          │            varchar            │  varchar  │  varchar  │      timestamp      │  varchar   │ varchar │                  varchar                   │  float  │
├────────────┼───────────┼──────────┼─────────────┼───────────────────────────────────────────────┼───────────┼──────────┼──────────┼───────────┼───────────────┼─────────┼──────┼────────────┼──────────────────┼──────────────┼────────────┼───────────────┼───────────┼──────────────────────────┼────────────────┼──────────┼───────────────────┼───────────────────────────┼───────────────────────────────┼───────────┼───────────┼─────────────────────┼────────────┼─────────┼────────────────────────────────────────────┼─────────┤
│         20 │        20 │    23517 │ 824-42-1232 │ FXHiaOLVYyWUGnRkdSXFJTTlkLDcGWtVQAMJZ         │         1 │ Active   │ Coppins  │ Drucill   │ NULL          │ M       │    3 │ 2008-11-07 │ 911 Topple Drive │ NULL         │ 21707      │ Winston-Salem │ OK        │ Canada                   │ (403) 386-7631 │ 964-5176 │ 057-4032          │ Drucill.Coppins@yahoo.com │ Drucill.Coppins@spamavert.com │ NB7       │ AB5       │ 2007-07-09 13:16:04 │ NEW        │ AB5     │ Alberta Income Tax for doctors and lawyers │    0.36 │
│         20 │       225 │    17367 │ NULL        │ dfVfLHXGTjNdVElVuqbLTqJjInRVFqwIoTdnRPFiCUQES │         1 │ Active   │ NULL     │ NULL      │ NULL          │ NULL    │ NULL │ NULL       │ NULL             │ NULL         │ NULL       │ NULL          │ NULL      │ NULL                     │ NULL           │ NULL     │ NULL              │ NULL                      │ NULL                          │ NULL      │ NULL      │ 2007-08-24 05:19:19 │ ADDACCT    │ NULL    │ NULL                                       │    NULL │
│         20 │      NULL │     NULL │ NULL        │ NULL                                          │      NULL │ Active   │ NULL     │ NULL      │ NULL          │ NULL    │    3 │ NULL       │ 14791 Bluff East │ NULL         │ M5D 1Y2    │ Orange        │ OR        │ United States of America │ 389-1326       │ 632-1025 │ +1 (489) 856-5017 │ Drucill.Coppins@post.com  │ NULL                          │ NULL      │ NULL      │ 2007-08-31 13:06:49 │ UPDCUST    │ NULL    │ NULL                                       │    NULL │
│         20 │      NULL │     NULL │ NULL        │ NULL                                          │      NULL │ Inactive │ NULL     │ NULL      │ NULL          │ NULL    │ NULL │ NULL       │ NULL             │ NULL         │ NULL       │ NULL          │ NULL      │ NULL                     │ NULL           │ NULL     │ NULL              │ NULL                      │ NULL                          │ NULL      │ NULL      │ 2007-09-06 01:42:46 │ INACT      │ NULL    │ NULL                                       │    NULL │
│         20 │        20 │     NULL │ NULL        │ NULL                                          │      NULL │ Inactive │ NULL     │ NULL      │ NULL          │ NULL    │ NULL │ NULL       │ NULL             │ NULL         │ NULL       │ NULL          │ NULL      │ NULL                     │ NULL           │ NULL     │ NULL              │ NULL                      │ NULL                          │ NULL      │ NULL      │ 2010-04-21 17:55:36 │ CLOSEACCT  │ NULL    │ NULL                                       │    NULL │
└────────────┴───────────┴──────────┴─────────────┴───────────────────────────────────────────────┴───────────┴──────────┴──────────┴───────────┴───────────────┴─────────┴──────┴────────────┴──────────────────┴──────────────┴────────────┴───────────────┴───────────┴──────────────────────────┴────────────────┴──────────┴───────────────────┴───────────────────────────┴───────────────────────────────┴───────────┴───────────┴─────────────────────┴────────────┴─────────┴────────────────────────────────────────────┴─────────┘

In [14]:
# Cust historical pipeline

customers = """ 
CREATE OR REPLACE TABLE customers AS
  SELECT
    customerid,
    taxid,
    status,
    lastname,
    firstname,
    middleinitial,
    gender,
    tier,
    dob,
    addressline1,
    addressline2,
    postalcode,
    city,
    stateprov,
    country,
    phone1,
    phone2,
    phone3,
    email1,
    email2,
    lcl_tx_id,
    nat_tx_id,
    1 batchid,
    update_ts
  FROM
    wh_db_stage.CustomerMgmt c
  WHERE
    ActionType in ('NEW', 'INACT', 'UPDCUST')
"""

con.sql(customers)
save_sql_to_file(customers, "wh_db.DimCustomer")

In [15]:
customers_final = """CREATE OR REPLACE TABLE customers_final AS
SELECT
    customerid,
    COALESCE(taxid, last_value(taxid ORDER BY update_ts DESC) OVER w) AS taxid,
    status,
    COALESCE(lastname, last_value(lastname ORDER BY update_ts DESC) OVER w) AS lastname,
    COALESCE(firstname, last_value(firstname ORDER BY update_ts DESC) OVER w) AS firstname,
    COALESCE(middleinitial, last_value(middleinitial ORDER BY update_ts DESC) OVER w) AS middleinitial,
    COALESCE(gender, last_value(gender ORDER BY update_ts DESC) OVER w) AS gender,
    COALESCE(tier, last_value(tier ORDER BY update_ts DESC) OVER w) AS tier,
    COALESCE(dob, last_value(dob ORDER BY update_ts DESC) OVER w) AS dob,
    COALESCE(addressline1, last_value(addressline1 ORDER BY update_ts DESC) OVER w) AS addressline1,
    COALESCE(addressline2, last_value(addressline2 ORDER BY update_ts DESC) OVER w) AS addressline2,
    COALESCE(postalcode, last_value(postalcode ORDER BY update_ts DESC) OVER w) AS postalcode,
    COALESCE(CITY, last_value(CITY ORDER BY update_ts DESC) OVER w) AS CITY,
    COALESCE(stateprov, last_value(stateprov ORDER BY update_ts DESC) OVER w) AS stateprov,
    COALESCE(country, last_value(country ORDER BY update_ts DESC) OVER w) AS country,
    COALESCE(phone1, last_value(phone1 ORDER BY update_ts DESC) OVER w) AS phone1,
    COALESCE(phone2, last_value(phone2 ORDER BY update_ts DESC) OVER w) AS phone2,
    COALESCE(phone3, last_value(phone3 ORDER BY update_ts DESC) OVER w) AS phone3,
    COALESCE(email1, last_value(email1 ORDER BY update_ts DESC) OVER w) AS email1,
    COALESCE(email2, last_value(email2 ORDER BY update_ts DESC) OVER w) AS email2,
    COALESCE(LCL_TX_ID, last_value(LCL_TX_ID ORDER BY update_ts DESC) OVER w) AS LCL_TX_ID,
    COALESCE(NAT_TX_ID, last_value(NAT_TX_ID ORDER BY update_ts DESC) OVER w) AS NAT_TX_ID,
    batchid,
    CASE 
        WHEN NULLIF(lead(update_ts) OVER w, NULL) IS NULL THEN 'Y' 
        ELSE 'N' 
    END AS iscurrent,
    update_ts::DATE AS effectivedate,
    COALESCE(lead(update_ts::DATE) OVER w, '9999-12-31'::DATE) AS enddate
FROM
    customers
WINDOW w AS (PARTITION BY customerid ORDER BY update_ts);"""

con.sql(customers_final)
save_sql_to_file(customers_final, "wh_db.DimCustomer")

In [16]:
# 
dimcustomer = """
INSERT INTO wh_db.DimCustomer (
    sk_customerid,
    customerid,
    taxid,
    status,
    lastname,
    firstname,
    middleinitial,
    gender,
    tier,
    dob,
    addressline1,
    addressline2,
    postalcode,
    city,
    stateprov,
    country,
    phone1,
    phone2,
    phone3,
    email1,
    email2,
    nationaltaxratedesc,
    nationaltaxrate,
    localtaxratedesc,
    localtaxrate,
    agencyid,
    creditrating,
    networth,
    marketingnameplate,
    iscurrent,
    batchid,
    effectivedate,
    enddate
)
WITH MaxSK AS (
    SELECT COALESCE(MAX(sk_customerid), 0) AS max_sk_customerid
    FROM wh_db.DimCustomer
),
CustomerData AS (
    SELECT 
        c.customerid,
        c.taxid,
        c.status,
        c.lastname,
        c.firstname,
        c.middleinitial,
        c.gender,
        c.tier,
        c.dob,
        c.addressline1,
        c.addressline2,
        c.postalcode,
        c.city,
        c.stateprov,
        c.country,
        c.phone1,
        c.phone2,
        c.phone3,
        c.email1, 
        c.email2,
        r_nat.TX_NAME as nationaltaxratedesc,
        r_nat.TX_RATE as nationaltaxrate,
        r_lcl.TX_NAME as localtaxratedesc,
        r_lcl.TX_RATE as localtaxrate,
        p.agencyid,
        p.creditrating,
        p.networth,
        p.marketingnameplate,
        c.iscurrent,
        c.batchid,
        c.effectivedate,
        c.enddate 
    FROM customers_final c
    JOIN wh_db.TaxRate r_lcl 
        ON c.lcl_tx_id = r_lcl.TX_ID
    JOIN wh_db.TaxRate r_nat 
        ON c.nat_tx_id = r_nat.TX_ID
    LEFT JOIN wh_db_stage.ProspectIncremental p 
        ON 
            UPPER(p.lastname) = UPPER(c.lastname)
            AND UPPER(p.firstname) = UPPER(c.firstname)
            AND UPPER(p.addressline1) = UPPER(c.addressline1)
            AND UPPER(NULLIF(p.addressline2, '')) = UPPER(NULLIF(c.addressline2, ''))
            AND UPPER(p.postalcode) = UPPER(c.postalcode)
    WHERE c.effectivedate < c.enddate
)
SELECT 
    ROW_NUMBER() OVER () + (SELECT max_sk_customerid FROM MaxSK) + 1 AS sk_customerid,
    c.customerid,
    c.taxid,
    c.status,
    c.lastname,
    c.firstname,
    c.middleinitial,
    IF(c.gender IN ('M', 'F'), c.gender, 'U') AS gender,
    c.tier,
    c.dob,
    c.addressline1,
    c.addressline2,
    c.postalcode,
    c.city,
    c.stateprov,
    c.country,
    c.phone1,
    c.phone2,
    c.phone3,
    c.email1, 
    c.email2,
    nationaltaxratedesc,
    nationaltaxrate,
    localtaxratedesc,
    localtaxrate,
    agencyid,
    creditrating,
    networth,
    marketingnameplate,
    iscurrent,
    batchid,
    effectivedate,
    enddate 
FROM CustomerData c;
 """

con.sql(dimcustomer)
save_sql_to_file(dimcustomer, "wh_db.DimCustomer")

In [17]:
con.sql("select * from wh_db.DimCustomer")

┌───────────────┬────────────┬─────────────┬──────────┬─────────────┬───────────┬───────────────┬─────────┬──────┬────────────┬───────────────────────────┬──────────────┬────────────┬────────────────┬───────────┬──────────────────────────┬───────────────────┬────────────────────────┬────────────────────────┬───────────────────────────────────┬────────────────────────────────┬──────────────────────────────────────────────────┬─────────────────┬────────────────────────────────────────────────┬──────────────┬──────────┬──────────────┬──────────┬─────────────────────────────────────────────────┬───────────┬─────────┬───────────────┬────────────┐
│ sk_customerid │ customerid │    taxid    │  status  │  lastname   │ firstname │ middleinitial │ gender  │ tier │    dob     │       addressline1        │ addressline2 │ postalcode │      city      │ stateprov │         country          │      phone1       │         phone2         │         phone3         │              email1               │             email2             │               nationaltaxratedesc                │ nationaltaxrate │                localtaxratedesc                │ localtaxrate │ agencyid │ creditrating │ networth │               marketingnameplate                │ iscurrent │ batchid │ effectivedate │  enddate   │
│     int64     │   int64    │   varchar   │ varchar  │   varchar   │  varchar  │    varchar    │ varchar │ int8 │    date    │          varchar          │   varchar    │  varchar   │    varchar     │  varchar  │         varchar          │      varchar      │        varchar         │        varchar         │              varchar              │            varchar             │                     varchar                      │      float      │                    varchar                     │    float     │ varchar  │    int32     │  int32   │                     varchar                     │  boolean  │  int32  │     date      │    date    │
├───────────────┼────────────┼─────────────┼──────────┼─────────────┼───────────┼───────────────┼─────────┼──────┼────────────┼───────────────────────────┼──────────────┼────────────┼────────────────┼───────────┼──────────────────────────┼───────────────────┼────────────────────────┼────────────────────────┼───────────────────────────────────┼────────────────────────────────┼──────────────────────────────────────────────────┼─────────────────┼────────────────────────────────────────────────┼──────────────┼──────────┼──────────────┼──────────┼─────────────────────────────────────────────────┼───────────┼─────────┼───────────────┼────────────┤
│             2 │        543 │ 210-66-6943 │ Active   │ Endsley     │ Deana     │ E             │ F       │    3 │ 1919-06-06 │ 9993 Kelvin Park          │ Apt. 177     │ V6B 1R4    │ Salt Lake City │ CA        │ United States of America │ 296-7192          │ 811-3213               │ NULL                   │ Deana.E.Endsley@wildmail.com      │ Deana.E.Endsley@deacons.com    │ Saskatchewan Income Tax for the elderly          │           0.355 │ Maine Income Tax for inherited wealth          │        0.085 │ end5     │          333 │  3064615 │ HighValue+Expenses+Boomer+MoneyAlert+Spender    │ true      │       1 │ 2008-02-24    │ 9999-12-31 │
│             3 │       6546 │ 137-03-3723 │ Active   │ Nickell     │ Fina      │ NULL          │ U       │    3 │ 1938-04-26 │ 19443 Payne Boulevard     │ Suite 386    │ 62705      │ Missoula       │ KS        │ United States of America │ (464) 603-6179    │ (562) 974-4206         │ +1 (452) 109-2019      │ Fina.Nickell@mail.be              │ Fina.Nickell@hotmail.com       │ Prince Edward Island Income Tax for the wealthy  │          0.4737 │ Idaho Income Tax for school teachers           │       0.0377 │ Nic8     │          761 │  1743614 │ HighValue+Expenses+Boomer+Spender               │ true      │       1 │ 2015-11-23    │ 9999-12-31 │
│             4 │       4354 │ 309-67-5285 │ Active   │ Disher      │ Tricci    │ NULL          │ F       │    3 │ 1918-05-03 │ 18335 Savannah Drive      │ Apt. 526     │ 73103      │ Cincinnati     │ TN        │ United States of America │ 662-9411          │ NULL                   │ NULL                   │ Tricci.Disher@hushmail.me         │ NULL                           │ Idaho Income Tax for blue collar workers         │          0.0554 │ Arkansas Tax for blue collar workers           │       0.0216 │ DIS16    │          817 │  2763009 │ HighValue+Expenses+Boomer+Spender               │ true      │       1 │ 2013-01-25    │ 9999-12-31 │
│             5 │        760 │ 828-41-7449 │ Active   │ Landaveri   │ Aryn      │ T             │ F       │    3 │ 1978-04-15 │ 165 Columbus Park         │ Apt. 309     │ H2F 1Z6    │ Lancaster      │ Alberta   │ United States of America │ 756-4180          │ NULL                   │ (553) 201-7392         │ Aryn.T.Landaveri@operamail.com    │ Aryn.T.Landaveri@dcemail.com   │ Missouri Income Tax for blue collar workers      │            0.06 │ North Dakota Income Tax for the masses         │         0.08 │ lan22    │          795 │  2041224 │ HighValue+Expenses+Spender                      │ true      │       1 │ 2008-06-05    │ 9999-12-31 │
│             6 │       2596 │ 914-41-0939 │ Active   │ Gutierrez   │ Ailina    │ NULL          │ F       │    3 │ 1944-03-31 │ 2572 Fresco Upper         │ Apt. 607     │ M1I 1R2    │ Las Vegas      │ UT        │ United States of America │ +1 (914) 401-2383 │ +1 (972) 014-8339      │ NULL                   │ Ailina.Gutierrez@taunusstein.net  │ NULL                           │ California Tax for blue collar workers           │          0.0764 │ Ontario Income Tax for the elderly             │       0.3122 │ GUT58    │          534 │   797918 │ HighValue+Boomer+MoneyAlert                     │ true      │       1 │ 2010-10-18    │ 9999-12-31 │
│             7 │        799 │ 510-48-7924 │ Active   │ Tymchuk     │ Conchita  │ H             │ M       │    3 │ 1955-09-16 │ 22636 Winsome Avenue      │ Apt. 3       │ V6Y 1T9    │ Missoula       │ RI        │ Canada                   │ NULL              │ NULL                   │ NULL                   │ Conchita.H.Tymchuk@lawyer.com     │ NULL                           │ Arizona Income Tax for inherited wealth          │          0.0504 │ Maryland Income Tax for inherited wealth       │       0.0485 │ Tym61    │          475 │  1284229 │ HighValue+Expenses+MoneyAlert+Spender+Inherited │ false     │       1 │ 2008-06-27    │ 2009-03-01 │
│             8 │       3208 │ 184-89-6699 │ Active   │ Graver      │ Thekla    │ M             │ U       │    3 │ 2016-07-25 │ 7903 Westerley Park       │ Apt. 117     │ 60766      │ Mesquite       │ Ontario   │ United States of America │ +1 (500) 639-1497 │ 553-8767               │ NULL                   │ Thekla.M.Graver@safe-mail.net     │ NULL                           │ Montana Income Tax for blue collar workers       │            0.02 │ Texas Income Tax for the masses                │          0.0 │ gra70    │          475 │  3850114 │ HighValue+Expenses+Boomer+MoneyAlert+Spender    │ true      │       1 │ 2011-08-02    │ 9999-12-31 │
│             9 │       1845 │ 331-20-2931 │ Active   │ Wroblewski  │ Patti     │ NULL          │ U       │    2 │ 2020-12-21 │ 10683 Curry Street        │ Suite 319    │ 45253      │ Jersey City    │ VA        │ United States of America │ 530-0137          │ 516-4263               │ NULL                   │ Patti.Wroblewski@peacemail.com    │ NULL                           │ U.S. Income Tax Bracket for the poor             │            0.15 │ Nunavut Income Tax for the masses              │        0.222 │ Wro107   │          403 │   247478 │ HighValue+Expenses+Boomer+MoneyAlert+Spender    │ false     │       1 │ 2009-11-01    │ 2012-12-05 │
│            10 │       6446 │ 123-82-2531 │ Active   │ Barraclough │ Karoly    │ I             │ U       │    1 │ 1991-01-19 │ 5052 California Lower     │ Apt. 573     │ V6S 1R5    │ Naperville     │ IA        │ United States of America │ 222-1808          │ 468-9386               │ +1 (323) 583-595596729 │ Karoly.I.Barraclough@dcemail.com  │ NULL                           │ Iowa Income Tax for the elderly                  │          0.0036 │ Manitoba Income Tax for everyone else          │        0.434 │ bar108   │          615 │  2750301 │ HighValue+Expenses+Inherited                    │ true      │       1 │ 2015-10-06    │ 9999-12-31 │
│            11 │       7453 │ 534-75-8073 │ Active   │ Abdou       │ Tchangid  │ NULL          │ M       │    3 │ 1962-10-19 │ 24695 Hampton Boulevard   │ Apt. 792     │ 80235      │ Shreveport     │ NV        │ United States of America │ +1 (747) 289-9257 │ (587) 738-1642         │ NULL                   │ Tchangid.Abdou@hush.ai            │ Tchangid.Abdou@deacons.com     │ British Columbia Income Tax for lawyers          │           0.265 │ New York Income Tax for inherited wealth       │       0.0685 │ Abd115   │          322 │  1069481 │ HighValue+Boomer+MoneyAlert                     │ true      │       1 │ 2017-01-22    │ 9999-12-31 │
│             · │         ·  │      ·      │   ·      │   ·         │    ·      │  ·            │ ·       │    · │     ·      │          ·                │  ·           │   ·        │    ·           │ ·         │            ·             │    ·              │    ·                   │  ·                     │           ·                       │  ·                             │               ·                                  │             ·   │                   ·                            │           ·  │  ·       │           ·  │       ·  │  ·                                              │  ·        │       · │     ·         │     ·      │
│             · │         ·  │      ·      │   ·      │   ·         │    ·      │  ·            │ ·       │    · │     ·      │          ·                │  ·           │   ·        │    ·           │ ·         │            ·             │    ·              │    ·                   │  ·                     │           ·                       │  ·                             │               ·                                  │             ·   │                   ·                            │           ·  │  ·       │           ·  │       ·  │  ·                                              │  ·        │       · │     ·         │     ·      │
│             · │         ·  │      ·      │   ·      │   ·         │    ·      │  ·            │ ·       │    · │     ·      │          ·                │  ·           │   ·        │    ·           │ ·         │            ·             │    ·              │    ·                   │  ·                     │           ·                       │  ·                             │               ·                                  │             ·   │                   ·                            │           ·  │  ·       │           ·  │       ·  │  ·                                              │  ·        │       · │     ·         │     ·      │
│          9992 │       5892 │ 018-27-9488 │ Active   │ Sfiroudis   │ Chrystel  │ NULL          │ M       │    3 │ 1924-04-22 │ 1063 Los Altos North      │ NULL         │ V6E 1T6    │ Edmonton       │ HI        │ United States of America │ 651-1896          │ 921-8418               │ NULL                   │ Chrystel.Sfiroudis@4uchat.de      │ NULL                           │ California Tax for the masses                    │          0.0432 │ Oregon Income Tax for inherited wealth         │         0.09 │ NULL     │         NULL │     NULL │ NULL                                            │ true      │       1 │ 2015-01-21    │ 9999-12-31 │
│          9993 │       6256 │ 317-53-7278 │ Active   │ Dupuis      │ Kare      │ NULL          │ M       │    3 │ 1977-02-15 │ 4669 Maple Rue            │ NULL         │ 48275      │ Edmonton       │ KY        │ Canada                   │ 442-5496          │ +1 (438) 114-3686      │ NULL                   │ Kare.Dupuis@gawab.com             │ Kare.Dupuis@mailmaniacs.com    │ Missouri Income Tax for the elderly              │           0.025 │ Oregon Income Tax for doctors and lawyers      │         0.07 │ NULL     │         NULL │     NULL │ NULL                                            │ true      │       1 │ 2015-07-11    │ 9999-12-31 │
│          9994 │       6396 │ 674-00-3478 │ Active   │ Riva        │ Shahram   │ NULL          │ U       │    2 │ 1984-12-12 │ 7557 Park Stream Street   │ NULL         │ 33311      │ Saint John     │ ID        │ United States of America │ 231-546624226     │ 907-7704               │ NULL                   │ Shahram.Riva@gmx.co.uk            │ Shahram.Riva@wraped.net        │ New Jersey Income Tax for doctors and lawyers    │          0.0438 │ Nunavut Income Tax for inherited wealth        │       0.4205 │ NULL     │         NULL │     NULL │ NULL                                            │ true      │       1 │ 2015-09-15    │ 9999-12-31 │
│          9995 │       7044 │ 262-31-5773 │ Active   │ Siomalas    │ Julia     │ Z             │ M       │    2 │ 1938-06-14 │ 11038 Panther Creek South │ NULL         │ M5A 1U3    │ Oceanside      │ FL        │ United States of America │ 864-7401          │ NULL                   │ (733) 725-6934         │ Julia.Z.Siomalas@mail2world.com   │ Julia.Z.Siomalas@enveloped.org │ California Tax for doctors and lawyers           │          0.0598 │ Minnesota Income Tax for inherited wealth      │       0.0785 │ NULL     │         NULL │     NULL │ NULL                                            │ true      │       1 │ 2016-07-17    │ 9999-12-31 │
│          9996 │         31 │ 407-60-4362 │ Active   │ Mia         │ Mysore    │ NULL          │ M       │    2 │ 1985-08-29 │ 24007 Minot South         │ NULL         │ M4J 1O7    │ Waco           │ FL        │ United States of America │ (984) 285-5249    │ 392-331874476          │ 221-0202               │ Mysore.Mia@shtrudel.net           │ NULL                           │ New Brunswick Income Tax for doctors and lawyers │            0.16 │ Hawaii Income Tax for the masses               │       0.0428 │ NULL     │         NULL │     NULL │ NULL                                            │ false     │       1 │ 2007-07-11    │ 2007-07-17 │
│          9997 │         97 │ 567-82-5598 │ Active   │ Moncion     │ Quon      │ Q             │ U       │    2 │ 1980-04-15 │ 21361 Canoas Crescent     │ NULL         │ 81007      │ Grand Prairie  │ NM        │ United States of America │ 934-5836          │ +1 (404) 227-868937487 │ NULL                   │ Quon.Q.Moncion@webmail.co.za      │ Quon.Q.Moncion@vfemail.net     │ Ohio Income Tax for everyone else                │          0.0541 │ Georgia Income Tax for inherited wealth        │         0.06 │ NULL     │         NULL │     NULL │ NULL                                            │ false     │       1 │ 2008-09-10    │ 2012-05-12 │
│          9998 │        969 │ 179-82-5497 │ Active   │ Okuzawa     │ Luce      │ NULL          │ U       │    2 │ 1955-01-26 │ 15276 Addison Crescent    │ NULL         │ 99576      │ Lewiston       │ VA        │ United States of America │ +1 (999) 975-9488 │ 994-2247               │ NULL                   │ Luce.Okuzawa@mailvault.com        │ NULL                           │ Virginia Income Tax for the masses               │            0.02 │ Prince Edward Island Income Tax for the masses │        0.308 │ NULL     │         NULL │     NULL │ NULL                                            │ false     │       1 │ 2008-09-12    │ 2009-01-17 │
│          9999 │        969 │ 179-82-5497 │ Inactive │ Okuzawa     │ Luce      │ NULL          │ U       │    2 │ 1955-01-26 │ 15276 Addison Crescent    │ NULL         │ 99576      │ Lewiston       │ VA        │ United States of America │ +1 (999) 975-9488 │ 994-2247               │ NULL                   │ Luce.Okuzawa@mailvault.com        │ NULL                           │ Virginia Income Tax for the masses               │            0.02 │ Prince Edward Island Income Tax for the masses │        0.308 │ NULL     │         NULL │     NULL │ NULL                                            │ true      │       1 │ 2012-12-11    │ 9999-12-31 │
│         10000 │       1053 │ 660-45-1898 │ Active   │ Mamoulides  │ Sohale    │ NULL          │ F       │    2 │ 1965-07-30 │ 15414 Alicia Drive        │ NULL         │ H6B 1X3    │ San Francisco  │ Alberta   │ United States of America │ 153-4329          │ 266-6163               │ NULL                   │ Sohale.Mamoulides@deadaddress.com │ NULL                           │ North Dakota Income Tax for everyone else        │          0.0933 │ Manitoba Income Tax for everyone else          │        0.434 │ NULL     │         NULL │     NULL │ NULL                                            │ false     │       1 │ 2008-10-24    │ 2013-10-17 │
│         10001 │       1285 │ 011-50-9938 │ Active   │ Felczak     │ Jenn      │ NULL          │ M       │    3 │ 1988-03-13 │ 931 Vendo Street          │ NULL         │ 90003      │ Vallejo        │ WI        │ United States of America │ 983-5736          │ +1 (502) 443-9848      │ +1 (896) 243-6066      │ Jenn.Felczak@bulldogs.com         │ NULL                           │ Yukon Income Tax for school teachers             │          0.1747 │ Delaware Income Tax for inherited wealth       │         0.06 │ NULL     │         NULL │     NULL │ NULL                                            │ true      │       1 │ 2011-10-11    │ 9999-12-31 │
├───────────────┴────────────┴─────────────┴──────────┴─────────────┴───────────┴───────────────┴─────────┴──────┴────────────┴───────────────────────────┴──────────────┴────────────┴────────────────┴───────────┴──────────────────────────┴───────────────────┴────────────────────────┴────────────────────────┴───────────────────────────────────┴────────────────────────────────┴──────────────────────────────────────────────────┴─────────────────┴────────────────────────────────────────────────┴──────────────┴──────────┴──────────────┴──────────┴─────────────────────────────────────────────────┴───────────┴─────────┴───────────────┴────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              33 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [30]:
import duckdb
db_path = 'initial_db.duckdb'
src_folder = 'src/data/Batch1'
con = duckdb.connect(database=db_path)

In [18]:
# kontrolli kui kõik FINWIRE on laetud
DimSecurity = """ 
INSERT INTO wh_db.DimSecurity
WITH SEC AS (
    SELECT
        recdate AS effectivedate,
        TRIM(SUBSTR(value, 1, 15)) AS Symbol,
        TRIM(SUBSTR(value, 16, 6)) AS issue,
        TRIM(SUBSTR(value, 22, 4)) AS Status,
        TRIM(SUBSTR(value, 26, 70)) AS Name,
        TRIM(SUBSTR(value, 96, 6)) AS exchangeid,
        TRY_CAST(SUBSTR(value, 102, 13) AS BIGINT) AS sharesoutstanding,
        TRY_CAST(STRPTIME(SUBSTR(value, 115, 8), '%Y%m%d') AS DATE) AS firsttrade,
        TRY_CAST(STRPTIME(SUBSTR(value, 123, 8), '%Y%m%d') AS DATE) AS firsttradeonexchange,
        TRY_CAST(SUBSTR(value, 131, 12) AS DOUBLE) AS Dividend,
        TRIM(CASE WHEN  regexp_matches(SUBSTR(value, -10), '^[0-9]+$') THEN  REGEXP_REPLACE(SUBSTR(value, -10), '^0+', '')
            ELSE SUBSTR(value, -60)
        end) as conameorcik
    FROM wh_db_stage.FinWire
    WHERE rectype = 'SEC'
),
dc AS (
    SELECT
        sk_companyid,
        name AS conameorcik,
        EffectiveDate,
        EndDate
    FROM wh_db.DimCompany
    UNION ALL
    SELECT
        sk_companyid,
        CAST(companyid AS VARCHAR) AS conameorcik,
        EffectiveDate,
        EndDate
    FROM wh_db.DimCompany
),
SEC_prep AS (
    SELECT
        SEC.* EXCLUDE (Status, conameorcik),
        COALESCE(TRY_CAST(conameorcik AS BIGINT)::VARCHAR, conameorcik) AS conameorcik,
        CASE 
            WHEN status = 'ACTV' THEN 'Active'
            WHEN status = 'CMPT' THEN 'Completed'
            WHEN status = 'CNCL' THEN 'Canceled'
            WHEN status = 'PNDG' THEN 'Pending'
            WHEN status = 'SBMT' THEN 'Submitted'
            WHEN status = 'INAC' THEN 'Inactive'
            ELSE NULL -- Or handle other cases
        END AS status,
        COALESCE(
            LEAD(effectivedate) OVER (PARTITION BY Symbol ORDER BY effectivedate),
            ('9999-12-31')::DATE
        ) AS enddate
    FROM SEC
),
        SEC_final AS (
    SELECT
        SEC.Symbol,
        SEC.issue,
        SEC.status,
        SEC.Name,
        SEC.exchangeid,
        dc.sk_companyid,
        SEC.sharesoutstanding,
        SEC.firsttrade,
        SEC.firsttradeonexchange,
        SEC.Dividend,
        CASE WHEN SEC.effectivedate < dc.EffectiveDate THEN dc.EffectiveDate ELSE SEC.effectivedate END AS effectivedate,
        CASE WHEN SEC.enddate > dc.EndDate THEN dc.EndDate ELSE SEC.enddate END AS enddate
    FROM SEC_prep SEC
    JOIN dc
        ON SEC.conameorcik = dc.conameorcik
        AND SEC.effectivedate < dc.EndDate
        AND SEC.enddate > dc.EffectiveDate
)
SELECT
    ROW_NUMBER() OVER () AS sk_securityid,
    Symbol,
    issue,
    status,
    Name,
    exchangeid,
    sk_companyid,
    sharesoutstanding,
    firsttrade,
    firsttradeonexchange,
    Dividend,
    CASE WHEN enddate = '9999-12-31'::DATE THEN TRUE ELSE FALSE END AS iscurrent,
    1 AS batchid,
    effectivedate,
    enddate
FROM SEC_final
WHERE effectivedate < enddate;


"""

con.sql(DimSecurity)
#save_sql_to_file(DimSecurity, "wh_db.DimSecurity")

In [19]:
con.sql("select * from wh_db.DimSecurity")

┌───────────────┬─────────────────┬─────────┬─────────┬───────────────────────────────────────────────────────────────────┬────────────┬──────────────┬───────────────────┬────────────┬──────────────────────┬──────────┬───────────┬─────────┬───────────────┬────────────┐
│ sk_securityid │     symbol      │  issue  │ status  │                               name                                │ exchangeid │ sk_companyid │ sharesoutstanding │ firsttrade │ firsttradeonexchange │ dividend │ iscurrent │ batchid │ effectivedate │  enddate   │
│     int64     │     varchar     │ varchar │ varchar │                              varchar                              │  varchar   │    int64     │       int64       │    date    │         date         │  double  │  boolean  │  int32  │     date      │    date    │
├───────────────┼─────────────────┼─────────┼─────────┼───────────────────────────────────────────────────────────────────┼────────────┼──────────────┼───────────────────┼────────────┼──────────────────────┼──────────┼───────────┼─────────┼───────────────┼────────────┤
│             1 │ AAAAAAAAAAAAABI │ COMMON  │ Active  │ NZUBULNTfJMTFoEUarvynPiwI whwReQkDNKlFBRjoMwRjkylDOZqkpLo         │ NASDAQ     │   1967033174 │         581301705 │ 1920-02-29 │ 1876-06-19           │     2.64 │ true      │       1 │ 1967-05-09    │ 9999-12-31 │
│             2 │ AAAAAAAAAAAAABL │ PREF_B  │ Active  │ NiCUPtADZazCucJvfWBWJkmPPMUZOvKfjDThHCiCdkppkJIkbnIOlFEGGPQuPMUSL │ PCX        │   2014123158 │         885559893 │ 1882-04-26 │ 1945-06-10           │     2.77 │ true      │       1 │ 2014-12-31    │ 9999-12-31 │
│             3 │ AAAAAAAAAAAAABS │ PREF_C  │ Active  │ HiKgKFhP E                                                        │ PCX        │   1970062722 │         544290590 │ 1898-05-22 │ 1916-12-19           │     2.19 │ true      │       1 │ 1970-06-27    │ 9999-12-31 │
│             4 │ AAAAAAAAAAAAACC │ COMMON  │ Active  │ iZRzCURRbFaVTkIgohCgZeKRvqHaUgqHUCtSeCYRpQgCnMeDP                 │ NASDAQ     │   1967032467 │         671877871 │ 1920-12-01 │ 1899-07-03           │     2.52 │ true      │       1 │ 1967-05-17    │ 9999-12-31 │
│             5 │ AAAAAAAAAAAAACP │ PREF_B  │ Active  │ aPKdlEKzyRMYUqNqBdunRiPOAFVABrXvyEQPKuOJeSaXlGOAZbEgny            │ NYSE       │   1967063010 │         799841233 │ 1936-08-25 │ 1919-08-11           │     1.69 │ true      │       1 │ 1967-06-30    │ 9999-12-31 │
│             6 │ AAAAAAAAAAAAACU │ COMMON  │ Active  │ QbCPjmsFcEcgpKWPAUEMMfzOiZyWIFeeHMLGRTSpYGSQIYPZJ                 │ NASDAQ     │   1967032973 │         695062051 │ 1910-01-04 │ 1884-11-07           │     0.76 │ false     │       1 │ 1967-05-24    │ 1977-09-30 │
│             7 │ AAAAAAAAAAAAACU │ COMMON  │ Active  │ SXRNDWytMAS                                                       │ NASDAQ     │   1967020125 │          64331595 │ 1969-12-25 │ 1965-12-26           │     1.44 │ true      │       1 │ 1977-09-30    │ 9999-12-31 │
│             8 │ AAAAAAAAAAAAADJ │ COMMON  │ Active  │ klPEzPcxPEiMELdaqgiXnGTpiSfLGhmdhINTUb yC                         │ PCX        │   1967021842 │         803840572 │ 1952-07-13 │ 1934-10-31           │     1.32 │ true      │       1 │ 1967-05-29    │ 9999-12-31 │
│             9 │ AAAAAAAAAAAAADU │ COMMON  │ Active  │ isaKgTEyNYeReGpwsWvkDywoePvThRSHpMwNi eyUFKkdnhEMxALeJXIv         │ NASDAQ     │   1967033174 │         491520032 │ 1861-11-23 │ 1886-11-26           │     1.48 │ true      │       1 │ 1967-06-03    │ 9999-12-31 │
│            10 │ AAAAAAAAAAAAADW │ PREF_B  │ Active  │ wQVIURZaKZubRnTsmOcMGioUUTWaMV                                    │ AMEX       │   1967091543 │         410170045 │ 1895-04-19 │ 1939-04-07           │     2.42 │ false     │       1 │ 1967-09-15    │ 1985-12-29 │
│             · │        ·        │   ·     │   ·     │       ·                                                           │  ·         │        ·     │              ·    │     ·      │     ·                │       ·  │  ·        │       · │     ·         │     ·      │
│             · │        ·        │   ·     │   ·     │       ·                                                           │  ·         │        ·     │              ·    │     ·      │     ·                │       ·  │  ·        │       · │     ·         │     ·      │
│             · │        ·        │   ·     │   ·     │       ·                                                           │  ·         │        ·     │              ·    │     ·      │     ·                │       ·  │  ·        │       · │     ·         │     ·      │
│          4692 │ AAAAAAAAAAAAFCS │ COMMON  │ Active  │ fHnLultUJJKMCR                                                    │ AMEX       │  19840929770 │           7161630 │ 1947-11-25 │ 1974-09-01           │     1.17 │ true      │       1 │ 2015-09-30    │ 9999-12-31 │
│          4693 │ AAAAAAAAAAAAFCZ │ COMMON  │ Active  │ NMpWcMIFQvvgHABRGKKFzE                                            │ AMEX       │ 200912301776 │         945463422 │ 1985-10-16 │ 1970-10-31           │     1.34 │ true      │       1 │ 2015-09-30    │ 9999-12-31 │
│          4694 │ AAAAAAAAAAAAFDT │ PREF_A  │ Active  │ CnfaNKa vIFIEjZfCNolMjJJc                                         │ NYSE       │  19720928290 │         129308411 │ 2000-10-16 │ 1970-06-22           │     0.76 │ true      │       1 │ 2015-12-31    │ 9999-12-31 │
│          4695 │ AAAAAAAAAAAAFEB │ COMMON  │ Active  │ JPGmFwgIfNRsfQUivLHBMUlrKj                                        │ AMEX       │   1977123161 │         733897822 │ 1985-01-26 │ 1853-10-31           │     1.69 │ true      │       1 │ 2016-03-30    │ 9999-12-31 │
│          4696 │ AAAAAAAAAAAAFEQ │ COMMON  │ Active  │ USNw gCCZpSV FpGarVPECCInDPHKeiQ VDpsVzX                          │ NYSE       │  19680913128 │         795596825 │ 1908-05-15 │ 1897-11-06           │     1.37 │ true      │       1 │ 2016-06-30    │ 9999-12-31 │
│          4697 │ AAAAAAAAAAAAFET │ COMMON  │ Active  │ SQFTSfEwPNHLhSxkZJHwJBxYYyvSTibZWzjEtctwNHidROuC                  │ NASDAQ     │ 200206291477 │         625696004 │ 1999-04-30 │ 1964-08-04           │      2.0 │ true      │       1 │ 2016-06-30    │ 9999-12-31 │
│          4698 │ AAAAAAAAAAAAFFR │ COMMON  │ Active  │ eAAySoTHVOlHcgyFOxvoAWOAtCTsPYNiEEXnbJtyQCreandTEascGQYPTUHt      │ PCX        │  19770929490 │          20393672 │ 1931-03-03 │ 1908-01-06           │     1.25 │ true      │       1 │ 2016-09-30    │ 9999-12-31 │
│          4699 │ AAAAAAAAAAAAFFX │ PREF_C  │ Active  │ fcAA rKkicawEgrAMygrVOoUILBBlSVwkVXLTiRGHHSpUtNWBEOPJnaRDvAiIRZng │ NYSE       │  19770924493 │         167616565 │ 1910-09-12 │ 1975-04-11           │     0.18 │ true      │       1 │ 2016-12-30    │ 9999-12-31 │
│          4700 │ AAAAAAAAAAAAFGZ │ COMMON  │ Active  │ vvWSyFPuCIRVdgYINQaFfBKJQGDutF UAgBzCRCkruHMTXAbEQukaDIo          │ NYSE       │  19871231897 │         947909841 │ 2014-08-04 │ 1949-10-19           │     0.35 │ true      │       1 │ 2017-03-31    │ 9999-12-31 │
│          4701 │ AAAAAAAAAAAAFHP │ COMMON  │ Active  │ qADI yuxJdSuHwbCRGqhZWSFafwgPlrYMEQmbl                            │ NASDAQ     │ 201203311870 │         192567333 │ 1899-06-14 │ 1934-05-28           │     2.93 │ true      │       1 │ 2017-06-30    │ 9999-12-31 │
├───────────────┴─────────────────┴─────────┴─────────┴───────────────────────────────────────────────────────────────────┴────────────┴──────────────┴───────────────────┴────────────┴──────────────────────┴──────────┴───────────┴─────────┴───────────────┴────────────┤
│ 4701 rows (20 shown)                                                                                                                                                                                                                                           15 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [20]:
con.sql("""     SELECT
distinct rectype
    FROM wh_db_stage.FinWire
     """)

┌───────────────┐
│    rectype    │
│    varchar    │
├───────────────┤
│ SEC           │
│ FIN_COMPANYID │
│ FIN_NAME      │
│ CMP           │
└───────────────┘

In [6]:
src_folder = 'src/data/Batch1'
file_path = os.path.join(src_folder, "TradeHistory.txt")
con.sql(f""" 

SELECT
*
FROM read_csv_auto('{file_path}', HEADER=FALSE, filename=false, all_varchar=true, columns = {{
    "tradeid": "BIGINT",
    "th_dts": "TIMESTAMP",
    "status": "STRING"
}})
""")

┌─────────┬─────────────────────┬─────────┐
│ tradeid │       th_dts        │ status  │
│  int64  │      timestamp      │ varchar │
├─────────┼─────────────────────┼─────────┤
│       0 │ 2012-07-07 00:00:47 │ SBMT    │
│       0 │ 2012-07-07 00:02:08 │ CMPT    │
│       1 │ 2012-07-07 00:06:15 │ SBMT    │
│       1 │ 2012-07-07 00:11:02 │ CMPT    │
│       2 │ 2012-07-07 00:06:57 │ PNDG    │
│       2 │ 2012-07-08 12:07:35 │ SBMT    │
│       2 │ 2012-07-08 12:11:23 │ CMPT    │
│       3 │ 2012-07-07 00:09:25 │ PNDG    │
│       3 │ 2012-09-15 11:35:22 │ SBMT    │
│       3 │ 2012-09-15 11:38:32 │ CMPT    │
│       · │          ·          │  ·      │
│       · │          ·          │  ·      │
│       · │          ·          │  ·      │
│    3938 │ 2012-07-18 01:46:57 │ PNDG    │
│    3938 │ 2012-07-30 02:40:00 │ SBMT    │
│    3938 │ 2012-07-30 02:41:57 │ CMPT    │
│    3939 │ 2012-07-18 01:51:32 │ PNDG    │
│    3939 │ 2012-09-08 16:39:12 │ CNCL    │
│    3940 │ 2012-07-18 01:52:23 │ PNDG    │
│    3940 │ 2012-09-17 21:51:20 │ SBMT    │
│    3940 │ 2012-09-17 21:53:22 │ CMPT    │
│    3941 │ 2012-07-18 01:59:06 │ PNDG    │
│    3941 │ 2012-09-23 06:03:48 │ SBMT    │
├─────────┴─────────────────────┴─────────┤
│      ? rows (>9999 rows, 20 shown)      │
└─────────────────────────────────────────┘

In [21]:
# DimAccount
DimAccount = """ 
INSERT INTO wh_db.DimAccount 
WITH account AS (
    SELECT
    accountid,
    customerid,
    accountdesc,
    taxstatus,
    brokerid,
    status,
    update_ts,
    1 batchid
from wh_db_stage.CustomerMgmt
where ActionType NOT IN ('UPDCUST', 'INACT')
  ),
account_final AS (
  SELECT
    accountid, -- Kept accountid as it's the partitioning key
    customerid,
    COALESCE(
        accountdesc,
        last_value(accountdesc) OVER w -- Retained  for correct logic
    ) AS accountdesc,
    COALESCE(
        taxstatus,
        last_value(taxstatus)  OVER w -- Retained 
    ) AS taxstatus,
    COALESCE(
        brokerid,
        last_value(brokerid)  OVER w -- Retained 
    ) AS brokerid,
    COALESCE(
        status,
        last_value(status)  OVER w -- Retained 
    ) AS status,
    batchid,
    CASE
        WHEN lead(update_ts) OVER w IS NULL THEN 'Y' -- Check if it's the last record in the partition
        ELSE 'N'
    END AS iscurrent,
    update_ts::DATE AS effectivedate, -- Using target format's casting style
    COALESCE(
        lead(update_ts::DATE) OVER w, -- Get next record's date within the partition
        '9999-12-31'::DATE           -- Default for the last record
    ) AS enddate
FROM
    account a -- Using the original table name
WINDOW w AS (
    PARTITION BY accountid -- Partitioning by the key from the original query
    ORDER BY update_ts     -- Ordering by the timestamp from the original query
 )
),
  account_cust_updates AS (
  SELECT
    a.* EXCLUDE (effectivedate, enddate, customerid),
    c.sk_customerid,
    if(
      a.effectivedate < c.effectivedate,
      c.effectivedate,
      a.effectivedate
    ) effectivedate,
    if(a.enddate > c.enddate, c.enddate, a.enddate) enddate
  FROM account_final a
  FULL OUTER JOIN wh_db.DimCustomer c 
    ON a.customerid = c.customerid
    AND c.enddate > a.effectivedate
    AND c.effectivedate < a.enddate
  WHERE a.effectivedate < a.enddate
)
SELECT
    CAST(strftime(a.effectivedate, '%Y%m%d') || a.accountid AS BIGINT),
    a.accountid,
    b.sk_brokerid, 
    a.sk_customerid,
    a.accountdesc,
    a.TaxStatus,
    a.status,
    -- Using standard CASE instead of IF() for iscurrent calculation
    CASE
        WHEN a.enddate = '9999-12-31'::DATE THEN true
        ELSE false
    END AS iscurrent,
    a.batchid,
    a.effectivedate,
    a.enddate
FROM
    account_cust_updates a
JOIN
    wh_db.DimBroker b ON a.brokerid = b.brokerid;
"""

con.sql(DimAccount)
save_sql_to_file(DimAccount, "wh_db.DimAccount")

In [ ]:
con.sql("select * from wh_db.DimAccount")

┌─────────┬─────────────────────┬─────────┐
│ tradeid │       th_dts        │ status  │
│  int64  │      timestamp      │ varchar │
├─────────┼─────────────────────┼─────────┤
│       0 │ 2012-07-07 00:00:47 │ SBMT    │
│       0 │ 2012-07-07 00:02:08 │ CMPT    │
│       1 │ 2012-07-07 00:06:15 │ SBMT    │
│       1 │ 2012-07-07 00:11:02 │ CMPT    │
│       2 │ 2012-07-07 00:06:57 │ PNDG    │
│       2 │ 2012-07-08 12:07:35 │ SBMT    │
│       2 │ 2012-07-08 12:11:23 │ CMPT    │
│       3 │ 2012-07-07 00:09:25 │ PNDG    │
│       3 │ 2012-09-15 11:35:22 │ SBMT    │
│       3 │ 2012-09-15 11:38:32 │ CMPT    │
│       · │          ·          │  ·      │
│       · │          ·          │  ·      │
│       · │          ·          │  ·      │
│    3938 │ 2012-07-18 01:46:57 │ PNDG    │
│    3938 │ 2012-07-30 02:40:00 │ SBMT    │
│    3938 │ 2012-07-30 02:41:57 │ CMPT    │
│    3939 │ 2012-07-18 01:51:32 │ PNDG    │
│    3939 │ 2012-09-08 16:39:12 │ CNCL    │
│    3940 │ 2012-07-18 01:52:23 │ PNDG    │
│    3940 │ 2012-09-17 21:51:20 │ SBMT    │
│    3940 │ 2012-09-17 21:53:22 │ CMPT    │
│    3941 │ 2012-07-18 01:59:06 │ PNDG    │
│    3941 │ 2012-09-23 06:03:48 │ SBMT    │
├─────────┴─────────────────────┴─────────┤
│      ? rows (>9999 rows, 20 shown)      │
└─────────────────────────────────────────┘

In [23]:
src_folder = 'src/data/Batch1'
file_path = os.path.join(src_folder, "Trade.txt")

# DimTrade
tradetxt = f""" 

CREATE OR REPLACE TABLE wh_db_stage.tradetxt AS 
SELECT * from  read_csv('{file_path}', HEADER=FALSE, filename=false, all_varchar=true, delim='|',strict_mode=false , columns = {{
    "tradeid": "BIGINT", 
    "t_dts": "TIMESTAMP",
    "status": "STRING", 
    "t_tt_id": "STRING",
    "cashflag": "TINYINT",
    "t_s_symb": "STRING",
    "quantity": "INT",
    "bidprice": "DOUBLE",
    "t_ca_id": "BIGINT",
    "executedby": "STRING",
    "tradeprice": "DOUBLE",
    "fee": "DOUBLE",
    "commission": "DOUBLE",
    "tax": "DOUBLE"}});

"""

src_folder = 'src/data/Batch1'
file_path = os.path.join(src_folder, "TradeHistory.txt")
tradehistory = f""" 
CREATE OR REPLACE TABLE wh_db_stage.tradehistory AS 
select * FROM read_csv_auto('{file_path}', HEADER=FALSE, filename=false, all_varchar=true, columns = {{
    "tradeid": "BIGINT", --TH_T_ID
    "th_dts": "TIMESTAMP", --TH_DTS
    "status": "STRING"}}); --TH_ST_ID

"""

con.sql(tradetxt)
save_sql_to_file(tradetxt, "wh_db_stage.tradehistory")
con.sql(tradehistory)
save_sql_to_file(tradehistory, "wh_db_stage.tradehistory")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
con.sql("select * from wh_db_stage.tradehistory")

In [25]:
DimTrade = f""" 
INSERT INTO wh_db.DimTrade
WITH tradehistorical AS (
select 
    a.tradeid,
    --brokerid
    CASE
    		WHEN b.status = 'SBMT' AND a.t_tt_id IN ( 'TMB', 'TMS' ) OR b.status = 'PNDG' THEN b.TH_DTS
			WHEN b.status IN ( 'CMPT', 'CNCL' ) THEN NULL
		END AS SK_CreateDateID
		, CASE 
			WHEN b.status = 'SBMT' AND a.t_tt_id IN ( 'TMB', 'TMS' ) OR b.status = 'PNDG' THEN b.TH_DTS
			WHEN b.status IN ( 'CMPT', 'CNCL' ) THEN NULL
		END AS SK_CreateTimeID
		, CASE 
			WHEN b.status = 'SBMT' AND a.t_tt_id IN ( 'TMB', 'TMS' ) OR b.status = 'PNDG' THEN NULL
			WHEN b.status IN ( 'CMPT', 'CNCL' ) THEN b.TH_DTS
		END AS SK_CloseDateID
		, CASE 
			WHEN b.status = 'SBMT' AND a.t_tt_id IN ( 'TMB', 'TMS' ) OR b.status = 'PNDG' THEN NULL
			WHEN b.status IN ( 'CMPT', 'CNCL' ) THEN b.TH_DTS
    END AS SK_CloseTimeID,
    c.st_name,
    CASE t_tt_id
      WHEN 'TMB' THEN 'Market Buy'
      WHEN 'TMS' THEN 'Market Sell'
      WHEN 'TSL' THEN 'Stop Loss'
      WHEN 'TLS' THEN 'Limit Sell'
      WHEN 'TLB' THEN 'Limit Buy'
    ELSE NULL -- Or some default value if needed
END AS type,
  a.cashflag,
  --ds.sk_securityid
  --ds.sk_companyid
  a.quantity,
  a.bidprice,
   -- sk_customerid
  -- sk_accountid
  a.executedby,
  a.tradeprice,
  a.fee,
  a.commission,
  a.tax,
  1 batchid,
  a.t_s_symb,
  a.t_ca_id
  from wh_db_stage.tradetxt a
  join wh_db_stage.tradehistory b
on a.tradeid = b.tradeid
  join wh_db.StatusType c -- ainult üks praegu
    ON a.status = c.st_id
)
select 
  trade.tradeid
  ,da.sk_brokerid
  ,CAST(strftime(trade.SK_CreateDateID, '%Y%m%d') || da.accountid || da.sk_brokerid AS BIGINT)
  ,CAST(strftime(trade.SK_CreateTimeID, '%Y%m%d') || da.accountid || da.sk_brokerid AS BIGINT)
  ,CAST(strftime(trade.SK_CloseDateID, '%Y%m%d') || da.accountid || da.sk_brokerid AS BIGINT)
  ,CAST(strftime(trade.SK_CloseTimeID, '%Y%m%d') || da.accountid || da.sk_brokerid AS BIGINT)
  ,trade.st_name
  ,trade.type
  ,trade.cashflag
  ,ds.sk_securityid
  ,ds.sk_companyid
  ,trade.quantity
  ,trade.bidprice
  ,da.sk_customerid
  ,da.sk_accountid
  ,trade.executedby
  ,trade.tradeprice
  ,trade.fee
  ,trade.commission
  ,trade.tax
  ,1 batchid
  
from tradehistorical trade
JOIN wh_db.DimSecurity ds
  ON 
    ds.symbol = trade.t_s_symb
    AND SK_CreateDateID::DATE >= ds.effectivedate 
    AND SK_CreateDateID::DATE < ds.enddate
JOIN wh_db.DimAccount da
  ON 
    trade.t_ca_id = da.accountid 
    AND SK_CreateDateID::DATE >= da.effectivedate 
    AND SK_CreateDateID::DATE < da.enddate;
        """

con.sql(DimTrade)
save_sql_to_file(DimTrade, "wh_db.DimTrade")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [26]:
con.sql("select * from wh_db.DimTrade")

┌─────────┬─────────────┬───────────────────┬───────────────────┬────────────────┬────────────────┬───────────┬─────────────┬──────────┬───────────────┬──────────────┬──────────┬──────────┬───────────────┬──────────────┬────────────┬────────────┬────────┬────────────┬──────────┬─────────┐
│ tradeid │ sk_brokerid │  sk_createdateid  │  sk_createtimeid  │ sk_closedateid │ sk_closetimeid │  status   │    type     │ cashflag │ sk_securityid │ sk_companyid │ quantity │ bidprice │ sk_customerid │ sk_accountid │ executedby │ tradeprice │  fee   │ commission │   tax    │ batchid │
│  int32  │    int64    │       int64       │       int64       │     int64      │     int64      │  varchar  │   varchar   │ boolean  │     int64     │    int64     │  int32   │  double  │     int64     │    int64     │  varchar   │   double   │ double │   double   │  double  │  int32  │
├─────────┼─────────────┼───────────────────┼───────────────────┼────────────────┼────────────────┼───────────┼─────────────┼──────────┼───────────────┼──────────────┼──────────┼──────────┼───────────────┼──────────────┼────────────┼────────────┼────────┼────────────┼──────────┼─────────┤
│   96565 │       14559 │  2013040455214559 │  2013040455214559 │           NULL │           NULL │ Canceled  │ Limit Sell  │ false    │          1154 │  19700617202 │      623 │     8.23 │          9452 │  20080104552 │ 23537      │       NULL │   NULL │       NULL │     NULL │       1 │
│   96569 │       24499 │ 20130404108224499 │ 20130404108224499 │           NULL │           NULL │ Completed │ Limit Sell  │ false    │           116 │  19741228383 │     9226 │     9.14 │          6336 │ 201005261082 │ 12213      │       9.18 │  343.6 │     161.39 │  9827.64 │       1 │
│   96573 │       24858 │  2013040476224858 │  2013040476224858 │           NULL │           NULL │ Completed │ Limit Sell  │ false    │          1150 │  19681225140 │     5958 │     9.28 │          6048 │  20080101762 │ 7256       │        9.7 │ 149.19 │     267.47 │  2959.48 │       1 │
│   96575 │       19618 │  2013040476819618 │  2013040476819618 │           NULL │           NULL │ Completed │ Limit Sell  │ false    │             4 │   1967032467 │      640 │     5.64 │          9674 │  20080103768 │ 16057      │       5.63 │  17.68 │        4.2 │   242.85 │       1 │
│   96579 │       20324 │  2013040448820324 │  2013040448820324 │           NULL │           NULL │ Completed │ Market Sell │ false    │          1790 │  19770629482 │     1950 │     8.75 │         10472 │  20100327488 │ 24254      │       8.57 │   30.6 │      60.92 │   5787.8 │       1 │
│   96581 │       20324 │  2013040448820324 │  2013040448820324 │           NULL │           NULL │ Completed │ Limit Sell  │ false    │          3501 │  19890929969 │     7616 │     2.07 │         10472 │  20100327488 │ 260        │        2.0 │  11.53 │      73.05 │  2786.93 │       1 │
│   96588 │        6571 │  2013040410696571 │  2013040410696571 │           NULL │           NULL │ Completed │ Market Buy  │ false    │          4339 │  19690320154 │     8019 │     2.83 │          2313 │ 201109201069 │ 9023       │       2.95 │  105.3 │      40.88 │  6821.62 │       1 │
│   96595 │       16217 │  2013040430516217 │  2013040430516217 │           NULL │           NULL │ Completed │ Market Sell │ false    │           724 │  19850928806 │     7757 │     2.02 │          5462 │  20090724305 │ 12445      │       1.98 │  26.75 │      58.57 │  5681.93 │       1 │
│   96603 │       22098 │   201304047922098 │   201304047922098 │           NULL │           NULL │ Completed │ Market Sell │ false    │          2403 │  19870330807 │     9939 │     7.11 │          9866 │   2009061479 │ 7188       │       7.08 │ 140.07 │     142.02 │  4993.68 │       1 │
│   96604 │       19171 │  2013040465119171 │  2013040465119171 │           NULL │           NULL │ Completed │ Market Buy  │ false    │          1571 │  19751229417 │     7388 │     8.87 │          4021 │  20080813651 │ 6345       │       8.71 │ 255.75 │      159.6 │ 19153.75 │       1 │
│     ·   │         ·   │          ·        │          ·        │             ·  │             ·  │     ·     │     ·       │   ·      │            ·  │       ·      │       ·  │       ·  │            ·  │       ·      │  ·         │         ·  │    ·   │         ·  │      ·   │       · │
│     ·   │         ·   │          ·        │          ·        │             ·  │             ·  │     ·     │     ·       │   ·      │            ·  │       ·      │       ·  │       ·  │            ·  │       ·      │  ·         │         ·  │    ·   │         ·  │      ·   │       · │
│     ·   │         ·   │          ·        │          ·        │             ·  │             ·  │     ·     │     ·       │   ·      │            ·  │       ·      │       ·  │       ·  │            ·  │       ·      │  ·         │         ·  │    ·   │         ·  │      ·   │       · │
│  161629 │       15235 │ 20131004175415235 │ 20131004175415235 │           NULL │           NULL │ Completed │ Limit Sell  │ false    │          1211 │  19781229541 │     3224 │     3.61 │          4505 │ 200906131754 │ 20287      │       3.79 │  54.44 │       47.1 │   2918.0 │       1 │
│  161636 │       22664 │ 20131004188222664 │ 20131004188222664 │           NULL │           NULL │ Completed │ Limit Buy   │ false    │           957 │  19871231896 │     5339 │      8.9 │          9847 │ 200809291882 │ 12806      │        8.5 │ 173.07 │      68.07 │ 13539.74 │       1 │
│  161638 │       12864 │ 20131004169212864 │ 20131004169212864 │           NULL │           NULL │ Completed │ Limit Buy   │ false    │          2369 │ 199109281054 │      874 │     5.69 │          7325 │ 201206071692 │ 11373      │       5.64 │   9.69 │      22.82 │  1882.85 │       1 │
│  161644 │       17868 │ 20131004180317868 │ 20131004180317868 │           NULL │           NULL │ Completed │ Market Buy  │ false    │          2370 │  19861231860 │     9461 │     3.07 │          8865 │ 201001181803 │ 6980       │       3.05 │  24.63 │     132.32 │  5953.79 │       1 │
│  161646 │        2395 │  2013100414452395 │  2013100414452395 │           NULL │           NULL │ Completed │ Limit Buy   │ false    │          3334 │  19710922255 │     7413 │      6.1 │          1571 │ 201111141445 │ 14785      │        6.0 │  121.4 │     112.58 │  9207.12 │       1 │
│  161648 │       16210 │ 20131004193016210 │ 20131004193016210 │           NULL │           NULL │ Completed │ Market Buy  │ false    │          1439 │  19860331835 │     1543 │     3.26 │           592 │ 200810111930 │ 14471      │       3.16 │  19.72 │       5.72 │  1173.48 │       1 │
│  161651 │        1041 │   201310047191041 │   201310047191041 │           NULL │           NULL │ Completed │ Limit Sell  │ false    │          2048 │  19721225297 │     1085 │     8.07 │          5519 │  20071222719 │ 14488      │       8.38 │  24.57 │      22.34 │   905.05 │       1 │
│  161653 │        9784 │  2013100410749784 │  2013100410749784 │           NULL │           NULL │ Completed │ Limit Sell  │ false    │          4569 │  20010629221 │     7135 │     5.35 │          4891 │ 201004271074 │ 23142      │       5.13 │ 128.85 │       51.4 │ 14425.76 │       1 │
│  161655 │        4531 │  2013100418844531 │  2013100418844531 │           NULL │           NULL │ Completed │ Market Sell │ false    │          2841 │  19770929490 │     8491 │     7.52 │          1131 │ 200809291884 │ 744        │       7.89 │ 152.39 │      40.98 │ 12978.89 │       1 │
│  161657 │       22170 │ 20131004135022170 │ 20131004135022170 │           NULL │           NULL │ Completed │ Limit Sell  │ false    │           318 │  19741230381 │     8887 │      4.4 │          5437 │ 201101091350 │ 18636      │       4.56 │  87.26 │       8.86 │  4601.65 │       1 │
├─────────┴─────────────┴───────────────────┴───────────────────┴────────────────┴────────────────┴───────────┴─────────────┴──────────┴───────────────┴──────────────┴──────────┴──────────┴───────────────┴──────────────┴────────────┴────────────┴────────┴────────────┴──────────┴─────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                      21 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [13]:
#SIIN TEMP
con.sql("""

WITH account AS (
    SELECT
    accountid,
    customerid,
    accountdesc,
    taxstatus,
    brokerid,
    status,
    update_ts,
    1 batchid
from wh_db_stage.CustomerMgmt
where ActionType NOT IN ('UPDCUST', 'INACT')
  ),
account_final AS (
  SELECT
    accountid, -- Kept accountid as it's the partitioning key
    customerid,
    COALESCE(
        accountdesc,
        last_value(accountdesc) OVER w -- Retained  for correct logic
    ) AS accountdesc,
    COALESCE(
        taxstatus,
        last_value(taxstatus)  OVER w -- Retained 
    ) AS taxstatus,
    COALESCE(
        brokerid,
        last_value(brokerid)  OVER w -- Retained 
    ) AS brokerid,
    COALESCE(
        status,
        last_value(status)  OVER w -- Retained 
    ) AS status,
    batchid,
    CASE
        WHEN lead(update_ts) OVER w IS NULL THEN 'Y' -- Check if it's the last record in the partition
        ELSE 'N'
    END AS iscurrent,
    update_ts::DATE AS effectivedate, -- Using target format's casting style
    COALESCE(
        lead(update_ts::DATE) OVER w, -- Get next record's date within the partition
        '9999-12-31'::DATE           -- Default for the last record
    ) AS enddate
FROM
    account a -- Using the original table name
WINDOW w AS (
    PARTITION BY accountid -- Partitioning by the key from the original query
    ORDER BY update_ts     -- Ordering by the timestamp from the original query
 )
),
  account_cust_updates AS (
  SELECT
    a.* EXCLUDE (effectivedate, enddate, customerid),
    c.sk_customerid,
    if(
      a.effectivedate < c.effectivedate,
      c.effectivedate,
      a.effectivedate
    ) effectivedate,
    if(a.enddate > c.enddate, c.enddate, a.enddate) enddate
  FROM account_final a
  FULL OUTER JOIN wh_db.DimCustomer c 
    ON a.customerid = c.customerid
    AND c.enddate > a.effectivedate
    AND c.effectivedate < a.enddate
  WHERE a.effectivedate < a.enddate
)
SELECT
    CAST(strftime(a.effectivedate, '%Y%m%d') || a.accountid AS BIGINT),
    a.accountid,
    b.sk_brokerid, 
    a.sk_customerid as "THIS_IS_SK_CUSTOMERID",
    a.accountdesc,
    a.TaxStatus,
    a.status,
    -- Using standard CASE instead of IF() for iscurrent calculation
    CASE
        WHEN a.enddate = '9999-12-31'::DATE THEN true
        ELSE false
    END AS iscurrent,
    a.batchid,
    a.effectivedate,
    a.enddate
FROM
    account_cust_updates a
JOIN
    wh_db.DimBroker b ON a.brokerid = b.brokerid;
""")

┌──────────────────────────────────────────────────────────────────────┬───────────┬─────────────┬───────────────────────┬────────────────────────────────────────────────────┬───────────┬─────────┬───────────┬─────────┬───────────────┬────────────┐
│ CAST((strftime(a.effectivedate, '%Y%m%d') || a.accountid) AS BIGINT) │ accountid │ sk_brokerid │ THIS_IS_SK_CUSTOMERID │                    accountdesc                     │ taxstatus │ status  │ iscurrent │ batchid │ effectivedate │  enddate   │
│                                int64                                 │   int64   │    int64    │         int64         │                      varchar                       │   int8    │ varchar │  boolean  │  int32  │     date      │    date    │
├──────────────────────────────────────────────────────────────────────┼───────────┼─────────────┼───────────────────────┼────────────────────────────────────────────────────┼───────────┼─────────┼───────────┼─────────┼───────────────┼────────────┤
│                                                         200904162639 │      2639 │        8808 │                    10 │ wOXBuTQgkNNsCnhomRPvkxuoHcUklVzZzvFOSHKtIOpJXPGud  │         2 │ Active  │ false     │       1 │ 2009-04-16    │ 2012-06-17 │
│                                                         201206172639 │      2639 │        8808 │                    11 │ wOXBuTQgkNNsCnhomRPvkxuoHcUklVzZzvFOSHKtIOpJXPGud  │         2 │ Active  │ false     │       1 │ 2012-06-17    │ 2013-10-11 │
│                                                         201310112639 │      2639 │        8808 │                    12 │ wOXBuTQgkNNsCnhomRPvkxuoHcUklVzZzvFOSHKtIOpJXPGud  │         2 │ Active  │ true      │       1 │ 2013-10-11    │ 9999-12-31 │
│                                                          20080902267 │       267 │       15347 │                    15 │ kEuomLkxXIvDgAjNo SeTJsfGVYKOTgVjISZupBGhdbAHJCy   │         1 │ Active  │ true      │       1 │ 2008-09-02    │ 9999-12-31 │
│                                                         200805291381 │      1381 │       22824 │                    17 │ ENJRCEgGNqRMNpVLmUZzprusWjSPNgHmx                  │         1 │ Active  │ false     │       1 │ 2008-05-29    │ 2017-01-27 │
│                                                         201701271381 │      1381 │       22824 │                    18 │ ENJRCEgGNqRMNpVLmUZzprusWjSPNgHmx                  │         1 │ Active  │ true      │       1 │ 2017-01-27    │ 9999-12-31 │
│                                                        2016022113033 │     13033 │       10596 │                    22 │ GriusuuWoqCvfRlShVSHIOaUiqdqSIzMShqQXWpGRhRP zLSDJ │         1 │ Active  │ true      │       1 │ 2016-02-21    │ 9999-12-31 │
│                                                          20100213962 │       962 │       17312 │                    23 │ CDmRVBMVoCLIXnLVxEKZwRcMmRSDQ Tqr                  │      NULL │ Active  │ false     │       1 │ 2010-02-13    │ 2015-06-16 │
│                                                          20150616962 │       962 │       17312 │                    24 │ CDmRVBMVoCLIXnLVxEKZwRcMmRSDQ Tqr                  │      NULL │ Active  │ true      │       1 │ 2015-06-16    │ 9999-12-31 │
│                                                          20070907280 │       280 │          28 │                    25 │ FEdKeESiKFillTHkEuUDTkMSAwN gve                    │         1 │ Active  │ false     │       1 │ 2007-09-07    │ 2008-12-25 │
│                                                               ·      │        ·  │           · │                     · │                ·                                   │         · │   ·     │  ·        │       · │     ·         │     ·      │
│                                                               ·      │        ·  │           · │                     · │                ·                                   │         · │   ·     │  ·        │       · │     ·         │     ·      │
│                                                               ·      │        ·  │           · │                     · │                ·                                   │         · │   ·     │  ·        │       · │     ·         │     ·      │
│                                                         201402029943 │      9943 │        9405 │                  5285 │ XqodBAawBTiWGJEiAC PKSBEUoOoROWbC                  │         2 │ Active  │ true      │       1 │ 2014-02-02    │ 9999-12-31 │
│                                                        2014022610038 │     10038 │       10701 │                  5286 │ NULL                                               │         1 │ Active  │ true      │       1 │ 2014-02-26    │ 9999-12-31 │
│                                                        2014022810046 │     10046 │       14416 │                  5287 │ GLcBXaVSbKWsRFaUtKmrdbhGFXBMWWX                    │         1 │ Active  │ true      │       1 │ 2014-02-28    │ 9999-12-31 │
│                                                        2014030910086 │     10086 │          89 │                  5288 │ BnHrStPSmcIhbZJLpsAAFETJLOpvgMUPGsZLKexjVoBQO      │         1 │ Active  │ true      │       1 │ 2014-03-09    │ 9999-12-31 │
│                                                        2014031610117 │     10117 │        1556 │                  5289 │ kSVGHrKMxXNJJYZtQLHAAOgI bXxFLNcRTH                │         2 │ Active  │ true      │       1 │ 2014-03-16    │ 9999-12-31 │
│                                                        2015100112443 │     12443 │       12066 │                  5290 │ NelPqSXDRTMdeoEExTbWyyIpooryLBpVTHNYOyaZsJ         │         1 │ Active  │ true      │       1 │ 2015-10-01    │ 9999-12-31 │
│                                                        2016021313009 │     13009 │       20624 │                  5291 │ BDVvexRbyiPqnjIcBIMxz dZbCyKhOpPBIvHhHUN           │         1 │ Active  │ true      │       1 │ 2016-02-13    │ 9999-12-31 │
│                                                        2014063010554 │     10554 │         100 │                  5292 │ IZGMHnRXMaorAynieTMKZNtkvzTQxD muStGoXxsMCTwNOqKyR │         2 │ Active  │ true      │       1 │ 2014-06-30    │ 9999-12-31 │
│                                                        2016071613634 │     13634 │        9381 │                  5293 │ NpuKMIAbbxlUCcFbAWeWVCfzqTrSMMMVBhjlb Un           │         1 │ Active  │ true      │       1 │ 2016-07-16    │ 9999-12-31 │
│                                                        2014042010260 │     10260 │       11418 │                  5294 │ EJrxcEnWBKZbhyjfyFSFVmQmJIHNVvOFOvkvfpFG           │         2 │ Active  │ true      │       1 │ 2014-04-20    │ 9999-12-31 │
├──────────────────────────────────────────────────────────────────────┴───────────┴─────────────┴───────────────────────┴────────────────────────────────────────────────────┴───────────┴─────────┴───────────┴─────────┴───────────────┴────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                             11 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [27]:
# FactCashBalances
src_folder = 'src/data/Batch1'
file_path = os.path.join(src_folder, "CashTransaction.txt")
FactCashBalances = f""" 
INSERT INTO wh_db.FactCashBalances
WITH historical AS (
    SELECT
        accountid,
        ct_dts::DATE AS datevalue,
        SUM(ct_amt) AS account_daily_total,
        1 batchid
    FROM read_csv(
        '{file_path}',
        HEADER=FALSE,
        columns={{'accountid': 'BIGINT', 'ct_dts': 'TIMESTAMP', 'ct_amt': 'DOUBLE', 'ct_name': 'VARCHAR'}}
    )
    GROUP BY ALL
  )
SELECT
    a.sk_customerid,
    a.sk_accountid,
    CAST(STRFTIME(datevalue, '%Y%m%d') AS BIGINT) AS sk_dateid,
    SUM(account_daily_total) OVER (PARTITION BY c.accountid ORDER BY datevalue) AS cash,
    c.batchid
FROM historical c
JOIN wh_db.DimAccount a
    ON c.accountid = a.accountid
    AND c.datevalue >= a.effectivedate
    AND c.datevalue < a.enddate;

    """

con.sql(FactCashBalances)
save_sql_to_file(FactCashBalances, "wh_db.FactCashBalances")

In [31]:
# replace filename
FactHoldings = f""" 
INSERT INTO wh_db.FactHoldings
WITH Holdings AS (
    SELECT
        *,
        1 AS batchid
    FROM read_csv(
        'src/data/Batch1\\HoldingHistory.txt',
        HEADER=FALSE,
        columns={{'hh_h_t_id': 'INTEGER', 'hh_t_id': 'INTEGER', 'hh_before_qty': 'INTEGER', 'hh_after_qty': 'INTEGER'}}
    )
)
SELECT
  hh_h_t_id tradeid,
  hh_t_id currenttradeid,
  sk_customerid,
  sk_accountid,
  sk_securityid,
  sk_companyid,
  sk_closedateid sk_dateid,
  sk_closetimeid sk_timeid,
  tradeprice currentprice,
  hh_after_qty currentholding,
  h.batchid
FROM Holdings h
  JOIN wh_db.DimTrade dt 
    ON tradeid = hh_t_id;
     """
con.sql(FactHoldings)
save_sql_to_file(FactHoldings, "wh_db.FactHoldings")

In [32]:
#replace table name
FactWatches = f""" 
INSERT INTO wh_db.FactWatches
WITH watchhistory AS (
    SELECT
        *,
        1 AS batchid
    FROM read_csv(
        'src/data/Batch1\\WatchHistory.txt',
        HEADER=FALSE,
        columns={{'w_c_id': 'BIGINT', 'w_s_symb': 'VARCHAR', 'w_dts': 'TIMESTAMP', 'w_action': 'VARCHAR'}}
    )
),
watches AS (
    SELECT
        wh.w_c_id AS customerid,
        wh.w_s_symb AS symbol,
        MIN(w_dts)::DATE AS dateplaced,
        CASE WHEN w_action = 'CNCL' THEN w_dts ELSE NULL END::DATE AS dateremoved,
        MIN(batchid) AS batchid
    FROM watchhistory wh
    GROUP BY ALL
)
select
  c.sk_customerid sk_customerid,
  s.sk_securityid sk_securityid,
  CAST(strftime(dateplaced, '%Y%m%d') AS BIGINT)  sk_dateid_dateplaced,
  CAST(strftime(dateremoved, '%Y%m%d') AS BIGINT) sk_dateid_dateremoved,
  wh.batchid 
from watches wh
JOIN wh_db.DimSecurity s 
  ON 
    s.symbol = wh.symbol
    AND wh.dateplaced >= s.effectivedate 
    AND wh.dateplaced < s.enddate
JOIN wh_db.DimCustomer c 
  ON
    wh.customerid = c.customerid
    AND wh.dateplaced >= c.effectivedate 
    AND wh.dateplaced < c.enddate;
"""
con.sql(FactWatches)
save_sql_to_file(FactWatches, "wh_db.FactWatches")

In [33]:

Financial = f""" 
INSERT INTO wh_db.Financial
WITH finwire_parsed AS (
    -- Parse the fixed-width data and extract relevant fields including conditional id/cname
    SELECT
        CAST(SUBSTRING(value FROM 1 FOR 4) AS INTEGER) AS fi_year,
        CAST(SUBSTRING(value FROM 5 FOR 1) AS INTEGER) AS fi_qtr,
        -- Explicitly cast strptime result to DATE if effectivedate/enddate are DATEs
        strptime(SUBSTRING(value FROM 6 FOR 8), '%Y%m%d')::DATE AS fi_qtr_start_date,
        CAST(SUBSTRING(value FROM 22 FOR 17) AS DOUBLE) AS fi_revenue,
        CAST(SUBSTRING(value FROM 39 FOR 17) AS DOUBLE) AS fi_net_earn,
        CAST(SUBSTRING(value FROM 56 FOR 12) AS DOUBLE) AS fi_basic_eps,
        CAST(SUBSTRING(value FROM 68 FOR 12) AS DOUBLE) AS fi_dilut_eps,
        CAST(SUBSTRING(value FROM 80 FOR 12) AS DOUBLE) AS fi_margin,
        CAST(SUBSTRING(value FROM 92 FOR 17) AS DOUBLE) AS fi_inventory,
        CAST(SUBSTRING(value FROM 109 FOR 17) AS DOUBLE) AS fi_assets,
        CAST(SUBSTRING(value FROM 126 FOR 17) AS DOUBLE) AS fi_liability,
        CAST(SUBSTRING(value FROM 143 FOR 13) AS BIGINT) AS fi_out_basic,
        CAST(SUBSTRING(value FROM 156 FOR 13) AS BIGINT) AS fi_out_dilut,
        -- Conditionally extract ID (as TEXT) or Name
        -- Ensure id and cname columns are mutually exclusive (one is NULL if other is not)
        CASE
            WHEN regexp_matches(SUBSTRING(value FROM -10), '^[0-9]+$')
            -- Remove leading zeros and trim; result is TEXT
            THEN trim(regexp_replace(SUBSTRING(value FROM -10), '^0+', ''))
            ELSE NULL
        END AS company_id_text,
        CASE
            WHEN NOT regexp_matches(SUBSTRING(value FROM -10), '^[0-9]+$')
            THEN trim(SUBSTRING(value FROM -60))
            ELSE NULL
        END AS company_name,
        -- Keep recdate for joining condition
        recdate
    FROM wh_db_stage.FinWire
    -- Filter record types early in the CTE
    WHERE rectype IN ('FIN_COMPANYID', 'FIN_NAME')
)
SELECT
    -- Select the SK from the successfully joined DimCompany record
    dc.sk_companyid,
    -- Select all parsed financial columns, excluding intermediate fields
    fp.* EXCLUDE (company_id_text, company_name, recdate)
FROM finwire_parsed AS fp
-- Use a single INNER JOIN (or LEFT JOIN if you need un-matched finwire rows)
JOIN wh_db.DimCompany AS dc
    -- Apply the date range filter first (can help with partitioning/pruning)
    ON fp.recdate >= dc.effectivedate
   AND fp.recdate < dc.enddate
    -- Apply the conditional join logic: match EITHER id OR name
   AND (
        (fp.company_id_text IS NOT NULL AND fp.company_id_text = dc.companyid::TEXT) -- Cast dc.companyid to TEXT if needed
        OR
        (fp.company_name IS NOT NULL AND fp.company_name = dc.name)
   );
"""

con.sql(Financial)
save_sql_to_file(Financial, "wh_db.Financial")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [40]:
src_folder = 'src/data/Batch1'
file_path = os.path.join(src_folder, "BatchDate.txt")
batch_number = int(''.join(filter(str.isdigit, os.path.basename(src_folder))))

con.sql(f"""
INSERT INTO wh_db.BatchDate
SELECT batchdate::DATE,
    {batch_number} AS batchid 
    FROM read_csv_auto('{file_path}', columns={{
    "batchdate": "DATE"
}}, header=False);
""")

In [41]:
# Prospect
Prospect = """
INSERT INTO wh_db.Prospect
WITH cust AS (
    SELECT
        lastname,
        firstname,
        addressline1,
        addressline2,
        postalcode
    FROM wh_db.DimCustomer
    WHERE iscurrent = 'Y'
)
SELECT
    p.agencyid,
    CAST(STRFTIME(recdate.batchdate, '%Y%m%d') AS BIGINT) AS sk_recorddateid,
    CAST(STRFTIME(origdate.batchdate, '%Y%m%d') AS BIGINT) AS sk_updatedateid,
    p.batchid,
    CASE WHEN c.LastName IS NOT NULL THEN TRUE ELSE FALSE END AS iscustomer,
    p.lastname,
    p.firstname,
    p.middleinitial,
    p.gender,
    p.addressline1,
    p.addressline2,
    p.postalcode,
    city,
    state,
    country,
    phone,
    income,
    numbercars,
    numberchildren,
    maritalstatus,
    age,
    creditrating,
    ownorrentflag,
    employer,
    numbercreditcards,
    networth,
    marketingnameplate
FROM wh_db_stage.ProspectIncremental p
JOIN wh_db.BatchDate recdate
    ON p.recordbatchid = recdate.batchid
JOIN wh_db.BatchDate origdate
    ON p.batchid = origdate.batchid
LEFT JOIN cust c
    ON
         UPPER(p.LastName) = UPPER(c.lastname)
        AND UPPER(p.FirstName) = UPPER(c.firstname)
        AND UPPER(p.AddressLine1) = UPPER(c.addressline1)
        AND UPPER(COALESCE(p.addressline2, '')) = UPPER(COALESCE(c.addressline2, ''))
        AND UPPER(p.PostalCode) = UPPER(c.postalcode)
         ;
"""

con.sql(Prospect)
save_sql_to_file(Prospect, "wh_db.Prospect")

In [46]:
con.close()

In [47]:

con_path = r"initial_db.duckdb"
con = duckdb.connect(con_path)
con.sql("CALL start_ui();")

┌───────────────────────────────────────────────────┐
│                      result                       │
│                      varchar                      │
├───────────────────────────────────────────────────┤
│ UI already running in a different DuckDB instance │
└───────────────────────────────────────────────────┘

In [2]:
con.close()

NameError: name 'con' is not defined

In [1]:
import duckdb

def run_duckdb_query():
    con_path = r"initial_db.duckdb"
    con = duckdb.connect(con_path)
    con.sql("CALL start_ui();")

if __name__ == "__main__":
    run_duckdb_query()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
# Customer hakkab alles batch2-st?

src_folder = 'src/data/Batch2'
file_path = os.path.join(src_folder, "Customer.txt")
batch_number = int(''.join(filter(str.isdigit, os.path.basename(src_folder))))

columns = {
    "cdc_flag": "VARCHAR",
    "cdc_dsn": "BIGINT",
    "customerid": "BIGINT",
    "taxid": "VARCHAR",
    "status": "VARCHAR",
    "lastname": "VARCHAR",
    "firstname": "VARCHAR",
    "middleinitial": "VARCHAR",
    "gender": "VARCHAR",
    "tier": "TINYINT",
    "dob": "DATE",
    "addressline1": "VARCHAR",
    "addressline2": "VARCHAR",
    "postalcode": "VARCHAR",
    "city": "VARCHAR",
    "stateprov": "VARCHAR",
    "country": "VARCHAR",
    "c_ctry_1": "VARCHAR",
    "c_area_1": "VARCHAR",
    "c_local_1": "VARCHAR",
    "c_ext_1": "VARCHAR",
    "c_ctry_2": "VARCHAR",
    "c_area_2": "VARCHAR",
    "c_local_2": "VARCHAR",
    "c_ext_2": "VARCHAR",
    "c_ctry_3": "VARCHAR",
    "c_area_3": "VARCHAR",
    "c_local_3": "VARCHAR",
    "c_ext_3": "VARCHAR",
    "email1": "VARCHAR",
    "email2": "VARCHAR",
    "lcl_tx_id": "VARCHAR",
    "nat_tx_id": "VARCHAR"
}

df = con.sql(f"SELECT * FROM read_csv('{file_path}', columns = $columns)", params={"columns": columns}).df()

print(df.dtypes)
print(df.head())

cdc_flag                 object
cdc_dsn                   int64
customerid                int64
taxid                    object
status                   object
lastname                 object
firstname                object
middleinitial            object
gender                   object
tier                       int8
dob              datetime64[us]
addressline1             object
addressline2             object
postalcode               object
city                     object
stateprov                object
country                  object
c_ctry_1                 object
c_area_1                 object
c_local_1                object
c_ext_1                  object
c_ctry_2                 object
c_area_2                 object
c_local_2                object
c_ext_2                  object
c_ctry_3                 object
c_area_3                 object
c_local_3                object
c_ext_3                  object
email1                   object
email2                   object
lcl_tx_id                object
nat_tx_id                object
dtype: object
  cdc_flag  cdc_dsn  customerid        taxid status   lastname firstname  \
0        U    10810        6737  061-42-7627   ACTV  Provencal     Laten
1        U    10811        2440  259-81-3662   ACTV      Leuty    Nguyet
2        U    10812        3701  287-28-9942   INAC     Sehgal   Mirabel
3        I    10813        7800  628-43-4159   ACTV  Osterhout    Blaine
4        I    10814        7801  909-06-8298   ACTV   Vendette     Joann

  middleinitial gender  tier  ... c_local_2 c_ext_2 c_ctry_3 c_area_3  \
0             J   None     2  ...  066-0546    None     None     None
1             H   None     3  ...  448-7075    None     None     None
2          None      M     3  ...  121-1224   37951     None     None
3          None   None     3  ...  824-9324    None     None     None
4          None      f     1  ...  650-1923    None     None     None

  c_local_3 c_ext_3                             email1  \
0      None    None     Laten.J.Provencal@hushmail.com
1  519-6150    None  Nguyet.H.Leuty@ProtectAnimals.com
2      None    None       Mirabel.Sehgal@spamavert.com
3      None    None      Blaine.Osterhout@hushmail.com
4      None    None           Joann.Vendette@gawab.com

                            email2 lcl_tx_id nat_tx_id
0                             None       ON3       AR5
1                             None       NS1       DE1
2                             None       KS3       PE8
3  Blaine.Osterhout@snail-mail.net       KY5       SK8
4                             None       MO7       NT1

[5 rows x 33 columns]

In [ ]:
# peale batch ingestionit täita ka wh_db.BatchDate

src_folder = 'src/data/Batch1'
file_path = os.path.join(src_folder, "BatchDate.txt")
batch_number = int(''.join(filter(str.isdigit, os.path.basename(src_folder))))

con.sql(f"""
INSERT INTO wh_db.BatchDate
SELECT batchdate::DATE,
    {batch_number} AS batchid 
    FROM read_csv_auto('{file_path}', columns={{
    "batchdate": "DATE"
}}, header=False);
""")

In [ ]:
con.close()

In [ ]:
template_name = "llm_prompt_for_column_level_lineage_easy"
llm_answers_dir = f"C:\lopu-kg-test\project\src\LLM_answers/{template_name}"
os.makedirs(llm_answers_dir, exist_ok=True)

In [ ]:
con = duckdb.connect(database=db_path)
#con.sql("select * from sqlite_temp_schema ")
con.sql("select column_name from information_schema.columns where table_name = 'ProspectIncremental'").df()

           column_name
0             agencyid
1             lastname
2            firstname
3        middleinitial
4               gender
5         addressline1
6         addressline2
7           postalcode
8                 city
9                state
10             country
11               phone
12              income
13          numbercars
14      numberchildren
15       maritalstatus
16                 age
17        creditrating
18       ownorrentflag
19            employer
20   numbercreditcards
21            networth
22  marketingnameplate
23       recordbatchid
24             batchid

In [ ]:
print(con.execute("select table_name, COLUMN_COMMENT from information_schema.columns").fetchdf())

    COLUMN_COMMENT
0             None
1             None
2             None
3             None
4             None
..             ...
421           None
422           None
423           None
424           None
425           None

[426 rows x 1 columns]

1. Information schemast tabelid ja skeemad sisse
2. Data pipelineid ja nende logimine, et pärast võrrelda LLM-i tulemusi päris tulemustega.
3. 

Küsimused:
1. Kas a la risk metric summa on alati numbriline väärtus?
2. Meil oleks vaja luua kontroll, et statustype ei tohi olla D, milliseid samme peaksime muutma?